### ISSUE TITLE
Provide hover to parsed tokens

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#107]
A use case where it might be useful to provide hover to parsed tokens is that user can check if a token exists in a context (rather than misspelled), and quickly show its definition (from assignment or function parameter).

**Comment by renkun-ken** [comment]
I did some experiment and I could implement the following:

1. Show last definition on hover

![image](https://user-images.githubusercontent.com/4662568/69417797-5bfde000-0d54-11ea-8144-a20555b3725d.png)


2. Show function argument documentation on hover

![image](https://user-images.githubusercontent.com/4662568/69417854-70da7380-0d54-11ea-9c1e-06b91862701d.png)

**Comment by randy3k** [comment]
Awesome!
