### ISSUE TITLE
show path in character autocompletion

### ISSUE THREAD

**Issue by gdkrmr** [REditorSupport/languageserver#109]
When typing something like
```
"R/fi
```
or
```
"/home/me/so
```
it would be great to complete the filename with the project folder as root and absolute file paths.

**Comment by renkun-ken** [comment]
I'm not sure if it should be provided by languageserver. A more general approach is to use such extension in your code editor. For example, I'm using VSCode and I use [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete) to provide completion for paths.

**Comment by renkun-ken** [comment]
Closing now.
