### ISSUE TITLE
Reduce the number of dependencies

### ISSUE THREAD

**Issue by nathaneastwood** [REditorSupport/languageserver#125]
Might you consider reducing the number of dependencies `languageserver` has? For example, `readr` is used and I see that it is one of the more recent commits whereby it replaced a base R function, thus the end user needs to also install `readr` in order to use `languageserver` because it now uses `reader::read_lines` and `readr::write_lines` over the base equivalents. Similarly `glue` and `stringr` could possibly be replaced with base alternatives.

**Comment by nathaneastwood** [comment]
I can always submit a PR to reduce the number of dependencies.

**Comment by randy3k** [comment]
It will require some careful crafting and benchmark. For `readr`, we will get rid of it entirely became the protocol actually does not assume we have access of the local files. We should always get all the disk information from the protocol.

**Comment by randy3k** [comment]
For stringr and glue, I am happy to replace them if it does not reduce readability and performance.

**Comment by nathaneastwood** [comment]
Great stuff 👍🏼
