### ISSUE TITLE
arg completion should not be provided in non-parentheses scope

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#126]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/4662568/70727622-ec6b8700-1d3a-11ea-8e8a-2df19183712c.png">

**Comment by randy3k** [comment]
it should be an easy pick.

**Comment by renkun-ken** [comment]
This issue is really about `document$detect_call` does not distinguish `f(|)`, `f({|})`, and `f([|])` where `|` is the cursor but it works with `f((|))` as expected.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/4662568/70758121-eb5b4980-1d7c-11ea-8929-dbd974f0d312.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/4662568/70758140-f44c1b00-1d7c-11ea-93e9-e078950e6dfa.png">

I think a general fix to this is to make `find_unbalanced_paren` work with `{}` and `[]` so that it detects the starting location and the type of the nearest parentheses, and arg completion should only be provided to `(` following a token as the function call.
