### ISSUE TITLE
fail to read from stdio at R 3.5

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/languageserver#13]
It seems that R 3.5 is somehow blocking the connection.

**Comment by randy3k** [comment]
It seems that the behavior of readLines() in R 3.5 has changed for non-blocking pipeline.

Consider the following R script, which reads from STDIN line by line.
```
con <- file("stdin")
open(con, blocking = FALSE)

while (TRUE) {
    txt <- readLines(con, 1)
    if (length(txt) > 0) {
        cat(txt, "\n", file = stdout())
    }
    Sys.sleep(0.1)
}
close(con)

```

In R 3.4.4, it works as expected.

```
(randymbpro)-Desktop$ echo "abc\nfoo" | R --slave -f test.R
abc
foo
```

In R 3.5, only the first line is printed
```
(randymbpro)-Desktop$ echo "abc\nfoo" | R --slave -f test.R
abc
```

**Comment by aenda** [comment]
On R 3.5, the language server fails to start for me, throwing
```
Error in self$read_content(nbytes) : Unexpected non-empty line
Error in self$read_content(nbytes) : Unexpected non-empty line

list()
exiting
```
Is this caused by this issue?

**Comment by randy3k** [comment]
Which editor are you using?

**Comment by aenda** [comment]
I'm using the neovim 0.2.2 release with LanguageClient-neovim 0.1.73. The errors occurs with a minimal configuration:
```
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'make release'}
call plug#end()
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {}
let g:LanguageClient_serverCommands.r = ['R', '--quiet', '--slave', '-e', 'languageserver::run()']
```
I installed the development version of this language server with
`source("https://install-github.me/REditorSupport/languageserver")`.

**Comment by randy3k** [comment]
yap, it looks like the cause of your issue. I am working on a fix, will post it tomorrow. I have to sleep now 😴

**Comment by randy3k** [comment]
11b357278c3febb7081f1af8b4bb069deefee473 should have fixed it. It would be great if you help testing it.

**Comment by aenda** [comment]
Using the same configuration as above, calling omnicompletion hangs until I C-c. The languageserver log is empty and the languageclient log shows
```
10:54:05 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Num(9)
Message: {"jsonrpc":2,"id":9,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1,"willSave":false,"willSaveWaitUntil":false,"save":{"includeText":false}},"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":"."},"signatureHelpProvider":{"triggerCharacters":["(",","]},"documentFormattingProvider":true,"documentRangeFormattingProvider":true}}}
Error: ErrorMessage { msg: "Invalid message of id: Num(9)" }
10:54:18 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Num(13)
Message: {"jsonrpc":2,"id":13,"result":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":10}},"newText":"a <- 1 + 1"}]}
Error: ErrorMessage { msg: "Invalid message of id: Num(13)" }
10:54:19 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Null
Message: {"jsonrpc":2,"method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/gmend/foo.R","diagnostics":[]}}
Error: ErrorMessage { msg: "Invalid message of id: Null" }
10:54:21 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Null
Message: {"jsonrpc":2,"method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/gmend/foo.R","diagnostics":[]}}
Error: ErrorMessage { msg: "Invalid message of id: Null" }
10:54:22 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Null
Message: {"jsonrpc":2,"method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/gmend/foo.R","diagnostics":[]}}
Error: ErrorMessage { msg: "Invalid message of id: Null" }
10:54:22 ERROR Handler-r src/vim.rs:349 Error handling message: Invalid message of id: Num(19)
Message: {"jsonrpc":2,"id":19,"result":{"isIncomplete":true,"items":[{"label":"colnames","kind":3,"detail":"{base}"}]}}
Error: ErrorMessage { msg: "Invalid message of id: Num(19)" }
```
The last line seems to be relevant, since I had typed in `coln` then called omni completion.

**Comment by randy3k** [comment]
Could you try again?

**Comment by randy3k** [comment]
Well, it does't seem to be working.

**Comment by aenda** [comment]
Yes, I'm still getting the "{ msg: "Invalid message of id: Num(#)" }" error message. Sorry for the delay in testing. I will file an issue on LanguageClient side to ask for help in debugging.

**Comment by randy3k** [comment]
I got the same error message. However, given that it runs on Sublime Text and Atom, I believe that is an issue of LanguageClient-Neovim.

**Comment by randy3k** [comment]
Oh, I check the difference between the messages between python language server and ours. And found this out 9cdf5dceea98bc681a78db48ab0befc25ef52efe.

![screen shot 2018-04-26 at 2 13 43 pm](https://user-images.githubusercontent.com/1690993/39323926-0bda2416-495c-11e8-8c58-6d661552eebf.png)
 
It is now working.
