### ISSUE TITLE
Arg completion no longer works for multi-lined parentheses

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#135]
Previously, signature and arg completion work for the following case:

```r
system.time({
}, gcFirst|)
```

where `|` is the cursor. It looks like it is caused by the changes made at #128.

When there are `{}`, `[]` or `()` positioned at two lines in the function call before the cursor, signature and arg completion no longer work.

**Comment by randy3k** [comment]
Ok, let me work on this.
