### ISSUE TITLE
Use TextDocumentSyncKind.Incremental 

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#146]
I'm wondering if it is possible to use `TextDocumentSyncKind.Incremental` update mode on `textDocument/didChange` to avoid the whole document being transferred repeatedly. When the document is large, the transfer looks a bit laggy.

**Comment by randy3k** [comment]
I think we just need to use `TextDocumentContentChangeEvent.range` and apply the changes correctly to `Document`.

**Comment by renkun-ken** [comment]
Yes, it saves a lot of unnecessary transfer of document and string split, and character vector copy, all of which are killing the performance.

**Comment by randy3k** [comment]
I don't think I have the time to implement it (plus the Sublime Text LSP client doesn't support incremental changes).

**Comment by renkun-ken** [comment]
Didn't know that incremental changes are not supported by all LSP-supporting editors. Is there a way for us to know whether the editor supports any LSP feature? (I guess `ServerCapabilities`?)

If there's a way to know if incremental changes is supported, I might have a try on it when I have time and see if it makes lsp more responsive for large documents.

**Comment by randy3k** [comment]
I think a cilent will only send incremental changes to the server if the server specifies `TextDocumentSyncKind` as `Incremental`.

Actually, it seems that `TextDocumentSyncKind` has been deprecated, the new value is `TextDocumentSyncOptions`.

**Comment by renkun-ken** [comment]
I quickly scanned https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/ and https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_synchronization and it looks like both `TextDocumentSyncOptions` and `TextDocumentSyncKind` are there but `TextDocumentSyncOptions` reduces some fields in the upcoming spec.

Another question related to such LSP change: I'm not sure should we follow the latest LSP or we just stick to a specific version of LSP? What's the typical policy of an average language server?

**Comment by randy3k** [comment]
LSP was version 2 When I started the project. To a large extent, LSP is quiet backward compatible so I am not too worried about breaking things. Of course, it is definitely a bad idea to chase the latest version of LSP. 

I don't think other servers have any policy at all and I don't want to impose hard requirements. The easy thing to do is follow VSCode as VSCode is the largest client of the LSP.

**Comment by renkun-ken** [comment]
Closing now as we won't implement it at the moment.
