### ISSUE TITLE
Remove document from workspace on didClose for non-package

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#147]
Previously, #123 enables removing objects in `GlobalNameSpace` when they are removed from document. However, when more and more documents are open in editor, the workspaces contains more and more documents, so that the completion provides more and more items. Even when most documents are closed, although they are removed from `documents`, they are still left in `Workspace`, which seems a bit inconsistent.

I'm not sure if it makes sense that if the workspace is not a package, then closing a document should remove the document from the workspace so that all relevant objects of the documents are removed.

**Comment by randy3k** [comment]
How about creating a `Workspace` for each individual file if the rootUri is not a package? I haven't given it a deep thought, but it seems reasonable.

Additionally, we could search for `source(...)` command to check if we need to import a workspace into another workspace.

**Comment by randy3k** [comment]
With #198, all relevant objects of a file will be removed if the file is closed except if it is from an R package.
