### ISSUE TITLE
Add support for sections

### ISSUE THREAD

**Issue by intiben** [REditorSupport/languageserver#160]
It would be very useful if sections could be defined in the R codes. These would allow to fold the code and to navigate through the script (e.g. the outline tab in VSCode).

In Rstudio one can define sections using comments followed by 4 or more +, - or = signs, here is an example of how it looks:

![Screen Shot 2020-01-17 at 10 44 35](https://user-images.githubusercontent.com/56064362/72601976-beb7c600-3916-11ea-8a54-876fad7622d2.png)

**Comment by andycraig** [comment]
These could be handled as Symbols. There’s a similar request over at vscode-R: https://github.com/Ikuyadeu/vscode-R/issues/76
