### ISSUE TITLE
A hover returns "Loading..." when Shift-JIS characters are used in vscode

### ISSUE THREAD

**Issue by takuizum** [REditorSupport/languageserver#164]
A hover returns "Loading..." when Shift-JIS characters are used on vscode.

I found **a small bug while using Japanese characters in vscode**, so I reported the details.
(I open same issue in R extension for vscode. [Here](https://github.com/Ikuyadeu/vscode-R/issues/194))

I used this package on vscode and found out that a hover (code completion) returns **"Loading..."** when Japanese characters (Shift-JIS) are entered, **although a hover works completely before putting the cursor on S-JIS character.**

Using this code, you could reproduce a bug above.

```
library() # A hover works well
set <- 1234 # A hover works well
set <- "abc" # A hover works well
set # Code completion works well

set <- "あいうえお" # Hovar retruns "Loaging..."
library() # Hovar retruns "Loaging...", too.
```

I confirmed setting.json and tried re-installing extensions and relevant package, but the problem was not improved.

My env is as below.

```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932
[3] LC_MONETARY=Japanese_Japan.932 LC_NUMERIC=C
[5] LC_TIME=Japanese_Japan.932

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base


loaded via a namespace (and not attached):
[1] compiler_3.6.2
```

More details, I use vscode-r version 1.2., R-LSP client version 0.1.4 and latest version of languageserver (in CRAN).

How can I solve this problem?

(This is my first issue report. I'm sorry if I could not give the necessary information.)

In my other device, it is macOS, I could not reproduce this bug. From the above, it seems to be particular to Windows 10 and not UTF-8 characters.

How can I solve this problem?

**Comment by randy3k** [comment]
languageserver expects  UTF-8 encoded documents. Are you saving the documents as UTF-8?

**Comment by takuizum** [comment]
Thanks for responding! @randy3k 

I use UTF-8 document, but OS system locale is Shift-JIS.

**Comment by randy3k** [comment]
Let me test it with a Windows VM.

**Comment by randy3k** [comment]
I finally figured out the cause of the error, which is basically https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17503

To put it in short, the string `あいうえお` would be printed as `<U+3042><U+3044><U+3046><U+3048><U+304A>` via the [`cat` function](https://github.com/REditorSupport/languageserver/blob/0798140d3607e431fd88f62a203618d0a3b566d2/R/languageserver.R#L111-L111) when the message is sent via the connection. As we need to count the number of bytes and the two representations give us a mismatch of the number of bytes, VScode was not able to receive any messages sent by the server.

We basically need a version of `cat` which sends raw utf-8 data, but as indicated by the R dev, it is not going to happen. One workaround is to escape all unicodes by `stringi::stri_escape_unicode`.

**Comment by randy3k** [comment]
I found another solution `writeLines(text, self$outputcon, sep = "", useBytes = TRUE)`

**Comment by takuizum** [comment]
I tried installing `languageserver` that is amended, then I have no problem!
```
devtools::install_github("REditorSupport/languageserver", ref = "7e04d0e162")
```
I appreciate your help @randy3k and @renkun-ken.

**Comment by randy3k** [comment]
I'm glad that the fix works for you.
