### ISSUE TITLE
Function completion should add parentheses

### ISSUE THREAD

**Issue by marskar** [REditorSupport/languageserver#167]
The current behavior is
`func` -> `function_name|` 
where `|` stands for the cursor position.

I prefer function completion to work like in RStudio and the [Python LSP with `python.autoComplete.addBrackets=true`](https://github.com/Microsoft/vscode-python/issues/2287):
`func` -> `function_name(|)`

I adapted the markdown in this issue from the [ncm-R README](https://github.com/gaalcaras/ncm-R).
I currently use ncm-R for R code completion. I would prefer to use LSP for all my completion needs. Is it possible for the R LSP to complete functions like the other projects I mentioned above?

**Comment by renkun-ken** [comment]
This can be easily implemented by the following changes in generating function completion items:

```r
functs_completions <- lapply(functs, function(object) {
                list(label = object,
                     kind = CompletionItemKind$Function,
                     detail = tag,
                     insertText = paste0(object, "($0)"),
                     insertTextFormat = InsertTextFormat$Snippet,
                     data = list(
                         type = "function",
                         package = nsname
                     ))
            })
```

However, selecting a function completion item does not trigger signature while user input of `(` does.

@randy3k Any thought on this?
