### ISSUE TITLE
Should to note install the binary version for the new user.

### ISSUE THREAD

**Issue by 8ar10der** [REditorSupport/languageserver#169]
I met a error today and solved it.

One of the dependent packages, 'stringi' does not work after updating to R3.2.1.

If new user normally install the languageserver will get the error when install "stringi". Then they have to reinstall R to reset the environment.

I recommend that pointing out this error and recommend that the user install the binary package.
`install.packages("languageserver",type="win.binary")` (for windows user, other platform user should change the type)

Or let user install binary "stringi" before install ‘languageserver“

See discuss here: https://stackoverflow.com/questions/31038636/package-stringi-does-not-work-after-updating-to-r3-2-1

**Comment by randy3k** [comment]
stringi was updated a while ago. For some reasons, stringi’s binary for R-latest is still not available on Windows https://cran.r-project.org/web/packages/stringi/index.html

I believe it’s a temporary thing and it will get resolved eventually.
