### ISSUE TITLE
[vscode] Code formatter to multiple lines (more then 3 lines) contain Japanese characters fails. 

### ISSUE THREAD

**Issue by takuizum** [REditorSupport/languageserver#170]
When I write or open the code contains Japanese characters and more than 3 lines with pipe concatenated, languageserver continues to report errors.

**Steps to reproduce the behavior:**

1. Write ( or open a code written) below lines
```
text <- "vscode is awesome"
text %>% str_replace_all("vscode", "ぶいえすこーど")  %>%
    str_replace_all("is", "は") %>%
    str_replace_all("awesome", "すばらしい")
```

Until line 2, languageserver works well. However, writing more than 3 lines, it continues showing error below.

```
[Error - 15:05:20] Request textDocument/rangeFormatting failed.
  Message: {"message":"missing value where TRUE/FALSE needed","call":{}}

  Code: -32603 
error handling json:  {"message":"lexical error: invalid char in json text.\n          \"縺吶<81><ef>��繧峨<ef>�<a0>縺Ы\")\\r\\n\"}]}}\n                     (right here) ------^\n","call":{}}

error handling json:  {"message":"lexical error: invalid char in json text.\n          \"縺吶<81><ef>��繧峨<ef>�<a0>縺Ы\")\\r\\nd\"}]}}\n                     (right here) ------^\n","call":{}}
```

I also record a screenshot (gif).
![vscode_completion_bug](https://user-images.githubusercontent.com/40698749/73333629-b7e16980-42ad-11ea-8cdf-11b1cd457c69.gif)

Although I tried the next conditions to reproduce this error, 

 - A large (more than 100) number of characters in one line.
 - Multiple lines without pipe

it cannot be observed.

**Environment (please complete the following information):**
 - OS: Windows 10 64 bit
 - VSCode Version 1.41.1
 - R Version3.6.2
 - latest vscode-r version
 - latest languageserver (installed from github repository)

Related issue in vscode
https://github.com/Ikuyadeu/vscode-R/issues/209

**Comment by randy3k** [comment]
It is again related to #164. When you paste a text, range formatting is requested. We use `styler` for formatting but however it seems that it doesn't handle unicodes correctly - the text returned by `styler::style_text` is converted to escaped unicodes.

```
r$> styler::style_text("'ぶい'")
"<U+3076><U+3044>"

r$> nchar(styler::style_text("'ぶい'"), type = "bytes")
[1] 18
```

A workaround is to turn off `format on paste` for now.

**Comment by randy3k** [comment]
@takuizum Could you reply the result of running
```
styler::style_text("'ぶい'")
nchar(styler::style_text("'ぶい'"), type = "bytes")
```
I suspect there is something else going on as I remember your system locale is  Japanese.

**Comment by takuizum** [comment]
@randy3k 
Sorry for the late reply!

I try installing languageserver, the version is you revised (https://github.com/REditorSupport/languageserver/commit/8adf71551f64e1df36f36910baacd52df21ccdde).

After then, I reopen vscode and R files, the bug seemed to be solved. I don't have any error from languageserver even if I open a problematic file.

At the end, I run the code you showed. The results were below.

```
r$> styler::style_text("'ぶい'")
    nchar(styler::style_text("'ぶい'"), type = "bytes")
"ぶい"
Warning message:
Could not use colored = TRUE, as the package prettycode is not installed. Please install it if you want to see colored output or see `?print.vertical` for more information. 
[1] 8
```

**Comment by randy3k** [comment]
I'm glad that the fix worked for you.

**Comment by takuizum** [comment]
Thank you for your kind advice.
