### ISSUE TITLE
Some providers not working on document initial open

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#173]
Currently, we use task manager to queue tasks such as parsing, linting, and resolving package dependencies. This makes languageserver responsive most of the time.

However, as a document is open, it triggers `textDocument/didOpen`, and some subsequent  requests such as `textDocument/documentLink` and `textDocument/documentSymbol` are sent immediately before the parsing completes. The result is, there's always no document symbol and document link after a document is open. I have to modify the document which triggers `textDocument/didChange` to also trigger `textDocument/documentSymbol` and `textDocument/documentLink` but they use an outdated XML parsed document.

I'm wondering if we could force the task manager to run in sync mode on `textDocument/didOpen` and in async mode on `textDocument/didChange`? Or do we have a better way to solve this on document initial open?

**Comment by randy3k** [comment]
Perhaps, we will need to write some mechanisms to allow deferring a reply to a later time. For example, 
- the request `textDocument/documentLink` is received
- check if we want to reply now
  - if yes, reply immediately
  - if no, defer the reply, say for 5 seconds.

We also need to avoid accumulating too many deferred replies.

**Comment by renkun-ken** [comment]
This sounds great to me.

>if no, defer the reply, say for 5 seconds.

I'm not sure how this can be implemented. Do you have anything in mind that we could _delay the reply_ somehow? If delaying is possible, the ideal way seems to be something like reactive programming in shiny, i.e. as long as the parsing completes, the `textDocument/documentLink` and `textDocument/documentSymbol` should be calculated. But a time delay is perfectly ok for me.

**Comment by randy3k** [comment]
The idea would be similar to the task manager. We might need to create a reply manager by attaching each reply with a checker. If the checker doesn't return true, we append the reply to a queue. The items in the queue will be processed in `process_events` cycle of the eventloop.

**Comment by renkun-ken** [comment]
For example, currently `textDocument/documentLink` relies on XML parsed  data (`xdoc`) of a document. If the checker only checks if `xdoc` exists, as long as the document is parsed for the first time, `xdoc` will always exist. When `textDocument/didChange` occurs, `textDocument/documentLink` will be triggered immediately before parsing is complete, but it will get an out dated `xdoc`. Does it mean that we also need to check if `xdoc` is sync in the checker?
