### ISSUE TITLE
.lintr config file only work if there is a trailing blank line

### ISSUE THREAD

**Issue by intiben** [REditorSupport/languageserver#185]
I was having a lot of issues setting up the `.lintr` config file (it was basically ignored by the R languageserver), but I figured out that I needed to have a trailing **blank line** at the end of the file. I put blank in bold there because having spaces on that blank line caused the linter to ignore the file for me.

An example of `.lintr` that doesn't work:
```
linters: with_defaults(line_length_linter(120))
```
An example that works:
```
linters: with_defaults(line_length_linter(120))

```

This is possibly related to #89

**Comment by renkun-ken** [comment]
Strange. I don't have a trailing blank line on ubuntu and macOS and both work for me.

**Comment by intiben** [comment]
I am also on maxOS, here is my session info if needed:
<details>
  <summary>SessionInfo()</summary>

```r

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lintr_2.0.0          languageserver_0.3.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       ps_1.3.0         withr_2.1.2      crayon_1.3.4     rprojroot_1.3-2  assertthat_0.2.1
 [7] R6_2.4.1         backports_1.1.5  magrittr_1.5     lazyeval_0.2.2   remotes_2.1.0    rstudioapi_0.10 
[13] callr_3.4.1      rex_1.1.2        xml2_1.2.2       cyclocomp_1.1.0  desc_1.2.0       tools_3.6.1     
[19] compiler_3.6.1   processx_3.4.1  
```
</details>

**Comment by intiben** [comment]
@renkun-ken the fix proposed above also worked for me on Ubuntu. 

Feel free to close the issue if you cannot reproduce it, if someone else runs into the same issue one day it could be re-opened.

**Comment by romunov** [comment]
Need a trailing blank line on Fedora (33).

```
lintr_2.0.1          languageserver_0.3.9
```
