### ISSUE TITLE
lsp-mode hangs with ess-r-mode: potential issues with languageserver

### ISSUE THREAD

**Issue by atanasj** [REditorSupport/languageserver#192]
This issues was originally posted at https://github.com/emacs-lsp/lsp-mode/issues/1383 and has the error log generated by `lsp-mode` associated with the issue.

I was advised to post the issue here as it seems to be a problem with `languageserver` and not the Emacs `lsp-mode` package. 

Please let me know if you need any further information.

**Comment by randy3k** [comment]
It seems the issue is that some empty replies are translated to `{}` instead of `[]` by jsonlite.

**Comment by renkun-ken** [comment]
Maybe we should return value in a stricter way?

```r
jsonlite::toJSON(list(id = 10, result = NULL))
#> {"id":[10],"result":{}}
jsonlite::toJSON(list(id = 10, result = list()))
#> {"id":[10],"result":[]}
jsonlite::toJSON(list(id = 10, result = character()))
#> {"id":[10],"result":[]}
```

**Comment by randy3k** [comment]
I guess we just need to check if result is NULL at https://github.com/REditorSupport/languageserver/blob/master/R/protocol.R#L89

**Comment by renkun-ken** [comment]
Is the following sufficient to solve the problem?

```r
payload <- list(
                jsonrpc = self$jsonrpc,
                id = self$id,
                result = as.list(self$result)
            )
```

If `self$result` is `NULL` then it would be converted to `list()`, then `jsonlite::toJSON` will tranlate it into `[]`.

**Comment by randy3k** [comment]
We’ll need to check if there is a reply expecting a dict result instead of an array result

**Comment by renkun-ken** [comment]
It looks like we can only check per handler and ensure to return `NULL` when dict result is expected and `list()` when array result is expected.

**Comment by randy3k** [comment]
Is there any way to get json's null?

**Comment by renkun-ken** [comment]
```r
jsonlite::toJSON(list(a = NULL), null = "null")
```

**Comment by randy3k** [comment]
I guess that’s the way to go.
