### ISSUE TITLE
Tooltip help should not appear for text in comments

### ISSUE THREAD

**Issue by Hong-Revo** [REditorSupport/languageserver#206]
I _think_ this is the right place for it....

![image](https://user-images.githubusercontent.com/11328890/74383725-de71d980-4e43-11ea-8add-de0094bf4cb4.png)

Here, you can see that VSCode has picked up on the word "range", and is displaying the R help for `range`. But the word is in a comment, and so shouldn't have any semantic meaning. Is it possible to get the language server to ignore comments?

**Comment by renkun-ken** [comment]
Are you using the latest languageserver? I could not reproduce this.

**Comment by Hong-Revo** [comment]
Updating to the latest version has indeed fixed this. Thanks for the heads up!
