### ISSUE TITLE
Language server should load package under development at startup

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#21]
Currently, the packages to load on startup of `languageserver` are those basic packages an fresh R session would attach.

If the project is a package (when `NAMESPACE` or `DESCRIPTION` is detected), the package should be loaded on startup too, to provide completion.

**Comment by randy3k** [comment]
The packages listed in `Depends` are now also loaded in v0.2.4.

We also need to read the `importFrom` lines from `NAMESPACE`. For example, `importFrom(R6,R6Class)` of the below file.

```
# Generated by roxygen2: do not edit by hand

export(run)
export(workspace_sync)
importFrom(R6,R6Class)
useDynLib(languageserver)

```

Shall we use `parse` to read this file? Or we just use regular expressions to search for matches?

**Comment by renkun-ken** [comment]
I think using parse seems to make it easier to handle user-written `NAMESPACE`.

`NAMESPACE` generated by roxygen2 is standard. We just need to handle the following forms:

```
import(package)
importFrom(package,function)
importFrom(package,"value<-")
```

But if `NAMESPACE` is manually created by user, the form can be wild but still valid:

```
^\s*import\s*\(\s*["']?package["']?\s*\)\s*$
^\s*importFrom\s*\(["']?package["']?\s*,\s*["']?function["']?\s*\)\s*$
```

For such consideration, I suggest using `parse` to simplify the reading.

**Comment by randy3k** [comment]
I think we could ignore `importFrom(package,"value<-")` because there are not much to do value assignments like this.

BTW, there is also `importFrom(magrittr,"%>%")`.

**Comment by renkun-ken** [comment]
It seems that some packages use more complicated `NAMESPACE` where exports are dynamically determined at installation time.

See https://github.com/Rdatatable/data.table/blob/master/NAMESPACE.

It seems that to correctly get all exported functions, `NAMESPACE` should be parsed and evaluated in a customized environment where `export` function is defined to collect all arguments.

**Comment by renkun-ken** [comment]
Closing as already fixed.
