### ISSUE TITLE
USE XDG config directory

### ISSUE THREAD

**Issue by klmr** [REditorSupport/languageserver#212]
The README says

> With lintr v2.0.0, the linters can be specified by creating the `.lintr` file at the project or home directory. 

Could this please be changed/extended to respect the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to avoid cluttering the home directory? That is, defaul to loading `${XDG_CONFIG_HOME-$HOME/.config}/lintr` and only if that doesn’t exist default to `$HOME/.lintr`.

**Comment by renkun-ken** [comment]
languageserver does not decide how lintr finds config path, it is implemented in `lintr:::find_config()`. You may raise issue at [lintr](https://github.com/jimhester/lintr)?

**Comment by klmr** [comment]
Thanks, I hadn’t found that in the lintr documentation.
