### ISSUE TITLE
normalizePath resolves symlinks and may cause inconsistencies

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#215]
In #202, we use `normalizePath(path, "/", mustWork = FALSE)` in `path_to_uri` to ensure that the path are all absolute and force `/` as described in <https://microsoft.github.io/language-server-protocol/specifications/specification-current/#uri>.

However, according to <https://stat.ethz.ch/R-manual/R-devel/library/base/html/normalizePath.html>, it also resolves symlink to the real path on linux and macOS. This may cause some potential inconsistencies in languageserver since a workspace or a document may be the symlink to another file.

We need to review the usage of `normalizePath`, `path_from_uri`, and `path_to_uri` and see if there could be potential problems.

**Comment by randy3k** [comment]
Actually, I was also thinking about it but decided that it was not very important (for me). Thank you for raising it anyway.

**Comment by renkun-ken** [comment]
One notable inconsistency is that under macOS, go to definition of a package function creates a temp file at e.g. `/var/folders/dh/6nhw4l5x0sq0wqgwh346fwjm0000gn/T/Rtmpkwxwlz/tempdir.R`. `normalizePath` resolves it to `/private/var/folders/dh/6nhw4l5x0sq0wqgwh346fwjm0000gn/T/Rtmpkwxwlz/tempdir.R` as noted in the documentation of the function.

**Comment by renkun-ken** [comment]
I create a symlink with

```sh
ln -s R/utils.R R/symlink.R
```

and restart editor and the following error occurs while loading all R files in package:

```
[2020-02-21 16:30:28.289] load  symlink.R

[2020-02-21 16:30:28.290] internal error: Error: '/Users/ken/Workspaces/github/languageserver/R/symlink.R' does not exist.
Stack trace:
1: stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
    getwd(), "')"), ".", call. = FALSE)
2: check_path(path)
3: standardise_path(file)
4: datasource(file, skip = skip, skip_empty_rows = skip_empty_rows)
5: readr::read_lines(path)
6: self$set_content(version, content)
7: .subset2(public_bind_env, "initialize")(...)
8: Document$new(uri, NULL, readr::read_lines(path))
9: dispatch(self, params)
```

**Comment by renkun-ken** [comment]
I reviewed all usages of `normalizePath`, `path_from_uri`, and `path_to_uri`, and it looks like most are fine except at https://github.com/REditorSupport/languageserver/blob/master/R/handlers-general.R#L34, if a symlink file exists, it will read the file into a new `Document` with the URI of the resolved path. But if user opens the symlink in editor, the file URI is not the resolved.

**Comment by randy3k** [comment]
By the way, why do you want the paths to be absolute?

**Comment by renkun-ken** [comment]
Although URI seems always to be absolute, it looks like we should not make it absolute in `path_to_uri` but assume the input has to be an absolute path already since there's no point to use the current working directory to make it absolute if the the input is relative.

Actually what I need is I have to rely on `normalizePath` to safely replace `\\` to `/` in the path under Windows. I'm not sure if it is safe to use `gsub("\\", "/", path, fixed = TRUE)` under Windows?

**Comment by randy3k** [comment]
With my understanding, `\` and `/` are interchangeable in most windows api. So it probably is fine.

**Comment by renkun-ken** [comment]
Accoding to <https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions>, it seems safe to replace all `\\` with `/` in Windows path. So we could make `path_to_uri` as the following:

```r
path_to_uri <- function(path) {
    if (length(path) == 0) {
        return(character())
    }
    path <- path.expand(path)
    if (.Platform$OS.type == "windows") {
        prefix <- "file:///"
        path <- gsub("\\", "/", path, fixed = TRUE)
    } else {
        prefix <- "file://"
    }
    paste0(prefix, utils::URLencode(path))
}
```

**Comment by randy3k** [comment]
Actually, unix filenames could contain `\n` and a lot of functions do not handle it probably. In general, we could only blame the user for picking such a filename.

**Comment by renkun-ken** [comment]
Fixed via 5941666e8d6e9949ea6c2e2436d2b0e0f4408b8d.

Now the only user-visible usage of `normalizePath` is https://github.com/REditorSupport/languageserver/blob/master/R/link.R#L23, which looks necessary if we don't want to import `fs::path_abs` since there could be all kinds of relative path in the document such as `source("../test.R")`. To get valid URI as document link target, we need to expand them to the full path.

**Comment by randy3k** [comment]
But you already did `file.path(root_path, str_texts[!is_abs_path])`. Isn’t that is sufficient?

**Comment by renkun-ken** [comment]
Consider something like `source("../test.R")`.

**Comment by randy3k** [comment]
In this case, we actually need `fs::path_norm`. But again, i don’t think we actually need to normalised it?

**Comment by renkun-ken** [comment]
I think in this case we need `fs::path_abs` to make it an abosulte path to make it a valid URI for document link target. `fs::path_norm` does not resolve `~`, `.` and `..` but only keep necessary parts such as trimming extra `/`.

**Comment by renkun-ken** [comment]
I tested with the latest commit under Windows 10 VM to see if #214 works but unfortunately, in Windows, VSCode uses lower-case schema in URI like

```
file:///c:/Users/ken/AppData/Local/Temp/RtmpInlIwy/normalizePath.R
```

while `dirname(tempdir())` returns

```
C:\\Users\\ken\\AppData\\Local\\Temp
```

Therefore, the `startWith` at https://github.com/REditorSupport/languageserver/blob/master/R/languageserver.R#L93 does not work in Windows due to inconsistency between lower and upper case of `C:/`.

**Comment by renkun-ken** [comment]
If `path_to_uri` uses `fs::path_expand()` which forces windows paths starting with upper-letter drive such as `C:/`, then package loading would be problematic since https://github.com/REditorSupport/languageserver/blob/master/R/handlers-general.R#L34 creates `Document` with the following URI:

```
C:/Users/ken/Workspaces/languageserver/R/utils.R
```

while opening the file the URI is actually

```
c:/Users/ken/Workspaces/languageserver/R/utils.R
```

Without `fs::path_expand()`, the URI is fortunately consistent since `rootUri` is `c:/Users/ken/Workspaces/languageserver` and both `file.path()` and `path_to_uri()` respect the original letter cases.
