### ISSUE TITLE
C functions and  "no visible binding ..." message

### ISSUE THREAD

**Issue by tjtnew** [REditorSupport/languageserver#227]
When using `.Call` my C functions are being highlighted with the `no visible binding for global variable` message.  This is when using VS code.  

For each function I have the corresponding `useDynLib` entry in my NAMESPACE and when using `devtools::check()` I am given no warnings.

Apologies if this is a misunderstanding on my part and not actually an issue with the languageserver.

**Comment by randy3k** [comment]
The error message comes from the diagnostics via lintr and lintr has a linter called `object_usage_linter`. There is not much we could do in `languageserver`. You could either disable the `object_usage_linter` linter or the diagnostics feature as a whole.

**Comment by renkun-ken** [comment]
According to https://github.com/jimhester/lintr#project-configuration and https://github.com/jimhester/lintr#configuration-2, to disable certain linters from default linters, you may create a `.lintr` file in your home folder (`~/.lintr`) or in your project folder.

For example, to disable `object_usage_linter`, `assignment_linter`, `commented_code_linter` and modify the line length linter to accept 120 characters:

```
linters: with_defaults(object_usage_linter = NULL, assignment_linter = NULL, commented_code_linter = NULL, line_length_linter(120))
```

To only enabled some wanted linters, use something like the following:

```
linters: list(commas_linter, equals_na_linter, infix_spaces_linter, no_tab_linter, seq_linter, spaces_inside_linter, T_and_F_symbol_linter)
```

https://github.com/jimhester/lintr#available-linters provides a full list of linters. If you are not sure about the name of the linter you want to disable, we are showing the linter name in the diagnostics via #220.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/4662568/75927973-675ebc80-5ea8-11ea-91a7-6ef62e08cdff.png">

You could also disable linters you don't want according to the linter names shown in diagnostics.

We may elaborate on this in the documentation some time.

**Comment by tjtnew** [comment]
Thank you that's really helpful.
