### ISSUE TITLE
Startup: `radian: error: no such option: --slave`

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/languageserver#228]
During startup in a remote session with {languageserver 0.3.4} and `radian` 0.4.7 I get

```
Usage: radian

radian: error: no such option: --slave

Language server exited with exit code 2
```

I have `r.lsp.debug` to TRUE but cannot track it down further. 

`rterm`  is set to `~/.local/bin/radian`.

Any ideas from your side what might be the problem?

**Comment by randy3k** [comment]
I assume that you are using VScode, as you have changed your default R console to radian, you would need to specify the path to the original R in `r.lsp.path`.

**Comment by renkun-ken** [comment]
`r.lsp.path` is used by vscode-r-lsp to start a languageserver session which is not intended for interactive use, should be original R executable path. If R is installed with default settings, user won't need to set this one.
`r.rterm.*` is used by vscode-R to find R terminal for interactive use, could be original R or radian.

We'll update the documentation at https://github.com/Ikuyadeu/vscode-R/wiki to make everything more clear.

**Comment by pat-s** [comment]
Thanks! I had set `r.lsp.path` when I opened this issue. After applying some changes I now have `languageserver` working and can't really traceback the initial error.
