### ISSUE TITLE
respect client capability of snippetSupport

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/languageserver#231]
see https://github.com/REditorSupport/languageserver/pull/168#issuecomment-598435170

**Comment by renkun-ken** [comment]
Let me work on this one.

**Comment by renkun-ken** [comment]
Somehow related to #225.

@krassowski If client has no `snippetSupport`, which function completion insert text makes more sense for you, `foo` or `foo(`?

**Comment by krassowski** [comment]
I would slightly prefer `foo` for compatibility reasons, but `foo(` should be ok too!

**Comment by renkun-ken** [comment]
So we use a plain `foo` as has been done in the PR for now if there's no `snippetSupport` unless we find a nice way to resolve #225.
