### ISSUE TITLE
.lintr defaults are not respected

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/languageserver#235]
I have a `.lintr` file in my repo root and running `lintr::lint_package()` works fine.

However, the disabled linters are not honored from languageserver and still appear in the problems pane.

`.lintr`

```
linters: with_defaults(assignment_linter = NULL, object_name_linter = NULL)
```

**Comment by randy3k** [comment]
What editor was it?

**Comment by pat-s** [comment]
Ups sorry, forgot that you do editor-agnostic work here -> vscode.

**Comment by randy3k** [comment]
By any chance, did you ever specified languageserver.default_linters in .Rprofile? That setting is now deprecated.

**Comment by renkun-ken** [comment]
I could reproduce this.

It's actually a bug on our side. Since we use `lintr::lint(text)` at https://github.com/REditorSupport/languageserver/blob/master/R/diagnostics.R#L94, it writes the content to a temp file and no longer finds the `.lintr` config as the original file.

Since there's no exported functions for us to get the linters specified in the right config file, fixing it would be a little tricky. Any good idea, @randy3k?

**Comment by randy3k** [comment]
I guess who could hack into https://github.com/jimhester/lintr/blob/1a7114b87c4d672772c74ffc30c932dcdb3ce017/R/settings.R#L64 to specify `lintr.linter_file`

**Comment by renkun-ken** [comment]
It looks we could safely specify `options(lintr.lintr_file)` in `diagnose_file` since it is run in a background process that does not affect the main process.

**Comment by renkun-ken** [comment]
I test with setting `options(lintr.linter_file)` in `diagnose_file` as implemented in #236 and it works nicely.

**Comment by pat-s** [comment]
Thanks for taking this on so quickly.

Unfortunately, linting is now completely broken for me (with latest dev).
I get 

> Failed to run diagnostics

in the "Problems" pane.

I had to roll back to b5ce3a8747a8ed5004521ceb2c1a05b5818e7635.

**Comment by renkun-ken** [comment]
@pat-s Would you like to turn on the R lsp debug and see the output of the languageserver. For example, if I put a `.lintr` that is not ended with a newline, then the diagnostics could fail with the following log:

```
[2020-03-20 19:33:58.370] diagnostics_task: <callr_status_error: callr subprocess failed: Malformed config file, ensure it ends in a newline
  zero-length inputs cannot be mixed with those of non-zero length>
 in process 
-->
<callr_remote_error: Malformed config file, ensure it ends in a newline
  zero-length inputs cannot be mixed with those of non-zero length>
 in process 48797 
```

To ensure your `.lintr` actually work, please check if your `.lintr` works with your file:

```r
lintr::lint("path/to/your_file.R")
```

**Comment by renkun-ken** [comment]
Looks like we should write the error message as the diagnostics message to make it easier to debug.

**Comment by renkun-ken** [comment]
d6dba1b8774832b67ecebf544211649d711507d9 shows the diagnostics error. Please try it and let us know the error shown as in the diagnostics.

**Comment by pat-s** [comment]
Thanks @renkun-ken for helping.

With latest dev, the diagnostic message I get is unfortunately not that much informative:

```
Failed to run diagnostics: callr subprocess failed: attempt to apply non-function
```

With languageserver diagnostics I get

```
<callr_remote_error in linters[[linter]](expr):
 attempt to apply non-function>
 in process 92379
```

Seems like something is wrong within the R script as I get

```r
lintr::lint("~/git/mlr3learners/mlr3learners.fnn/R/LearnerClassifFNN.R")                                                    
Error in linters[[linter]](expr) : attempt to apply non-function
```

[File](https://github.com/mlr3learners/mlr3learners.fnn/blob/469942fd634cfabd266a8aef4fb37380eb00e2a6/R/LearnerClassifFNN.R)

The call works with default linters, i.e. `linters: with_defaults()` in `.lintr`.

This is also fine `linters: with_defaults(assignment_linter = NULL)`

And the following causes the issue: `linters: with_defaults(object_name_linter = c("snake_case", "CamelCase"))`

---

I think it is an {lintr} issue: https://github.com/jimhester/lintr/issues/471

Nevertheless the latest changes should help users tracking down issues in the future! Thanks.
