### ISSUE TITLE
[vscode] "Surround" support

### ISSUE THREAD

**Issue by pat-s** [REditorSupport/languageserver#237]
Even though I mostly use vim-surround, I noticed that there is no native "surround" support for R within vscode by default (i.e. not in vim mode).

Seems like this needs to be added on a [per language base](https://stackoverflow.com/questions/42363030/visual-studio-code-surround-with).

**Comment by randy3k** [comment]
It is not in the scope of languageserver unfortunately. Check with vscode-R.

**Comment by pat-s** [comment]
Thanks!
