### ISSUE TITLE
show preview of variables if set?

### ISSUE THREAD

**Issue by biocyberman** [REditorSupport/languageserver#244]
I am checking emacs+ESS+LSP backend. It looks very promising. However, there are couple of reasons that I don't see myself using it for daily yet:

1. Speed: The tooltip popup and `lintr` is two aggressive to show every single details. And it makes the interface sluggish over an SSH session. I wish to have a way to specify what I need to `lint`. I am checking out [`lintr`](https://github.com/jimhester/lintr) package, but haven't got things to work and hope to find a simpler way. 
2. Preview of variables: LSP is showing variable assignment statement at the cursor. If the variable is set, it will be really nice to show their values or preview or their values (i.e. `head` or `str`) similar to the output of ESS `describe-object-at-point` function. The assignment can be view by other short cut key already, so it doesn't have to be the default value.

**Comment by biocyberman** [comment]
Ok, number one could be at least manually set and improved a bit by following this guide: https://github.com/REditorSupport/languageserver#customizing-server-capbabilities

**Comment by renkun-ken** [comment]
> I wish to have a way to specify what I need to lint

You may want to create a `.lintr` file per project or globally (`~/.lintr`) to disable unwanted linters or enable only wanted linters. Please see https://github.com/jimhester/lintr#project-configuration for more details.

>... If the variable is set, it will be really nice to show their values or preview or their values (i.e. head or str) similar to the output of ESS describe-object-at-point function.

A variable is only set in a live R session. At the moment, languageserver only does static analysis, i.e. analyzing code without any connection to any live R session which makes languageserver independent of user session and knows nothing about the value of any variable in user session.

If you find it sluggish on your machine or via SSH, you could always disable any language server providers you don't need using `options(languageserver.server_capabilities=)` as you mentioned.

**Comment by biocyberman** [comment]
Now I understood what the word 'static' in `lintr` means.  Thanks.
