### ISSUE TITLE
Closures aren't recognised as functions / symbols

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/languageserver#254]
This may be a bit too niche to solve but thought I'd flag it anyway just encase.

Essentially closures aren't recognised as functions / symbols within vs code.  I.e.

```
x <- function(){
    function() print("hello world")
}

y <- x()
```

Then when doing a symbol search in the command palette it will only show x as a defined function

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (5 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

(Copied over from: https://github.com/Ikuyadeu/vscode-R/issues/322  )

**Comment by randy3k** [comment]
I am glad that you recognize that it is hard to fix. There are a million ways to create user functions including `rlang::new_function()`, `eval()` etc...

It is almost impossible to cover all cases.

**Comment by renkun-ken** [comment]
With #295, `y` will be shown too but as a variable rather than a function.

**Comment by renkun-ken** [comment]
Closing now.
