### ISSUE TITLE
Rmd Color coding doesn't work if there is a space after the backticks and the bracket

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/languageserver#255]
Rmd color coding doesn't work in vscode if there is a space between the backticks and the bracket.

With space:

![image](https://user-images.githubusercontent.com/8447209/82070984-5ebb0b80-96cd-11ea-8a34-4a5e09798e00.png)

without space:
![image](https://user-images.githubusercontent.com/8447209/82071409-f6205e80-96cd-11ea-861e-07d3341a4385.png)

Apparently this is still valid for Rmd and will still render without issue -.-

**Comment by randy3k** [comment]
languageserver doesn’t handle syntax highlight. You should file an issue to your editor.

Related to this, our markdown support does not handle chunk with an space.

**Comment by gowerc** [comment]
O, I was forwarded here from the vscore-R package which has the following in their issue template

```
<!-- Is the issue about auto-completion, hover help, go to definition,
  document highlight,  document outline/symbols, workspace symbols, formatting, 
  document link, document color and color picker?
  If so it is more likely an issue with the language server.
  Please report issue at <https://github.com/REditorSupport/languageserver/issues>. -->
```

> Related to this, our markdown support does not handle chunk with an space.

Is there any chance it could support markdown with a space ?

**Comment by randy3k** [comment]
I see, "document highlight" means a different thing in this context. It refers to the highlight of the symbols in LSP.

**Comment by renkun-ken** [comment]
Looks like Rmd chunk could start with "`{3,}\s*{", all marked as code chunk in RStudio and valid for knitr to render.

@randy3k Should we adjust the Rmd chunk regex to be consistent with RStudio and knitr?

**Comment by randy3k** [comment]
Sure, it should be an easy pick. Relevant lines:

https://github.com/REditorSupport/languageserver/blob/master/R/utils.R#L109
https://github.com/REditorSupport/languageserver/blob/master/R/utils.R#L138

**Comment by renkun-ken** [comment]
As for syntax highlighting, will be fixed at vscode-R (https://github.com/Ikuyadeu/vscode-R/issues/326#issuecomment-629555800).
