### ISSUE TITLE
"Language server rlang has crashed"

### ISSUE THREAD

**Issue by eteitelbaum** [REditorSupport/languageserver#262]
Hello,

Whenever I open an .R or .Rmd file in Sublime Text 3 I get the message "Language server rlang has crashed, do you want to restart it?" When I click 'Restart' it gives me the same message. What could be the problem? 

Thanks!

**Comment by randy3k** [comment]
Are there any errors in LSP log panel?

**Comment by eteitelbaum** [comment]
Where do I find the LSP log panel?

**Comment by randy3k** [comment]
Actually I meant in the sublime console. You should enable these settings in LSP,

```
	"log_debug": true,
	"log_server": true,
	"log_stderr": true,
```
and report when you see in the console.

**Comment by eteitelbaum** [comment]
Thanks, Randy. This is what I see:

`LSP: LanguageHandler instantiation crashed! list index out of range
LSP: received config rlang from LspRLangPlugin
LSP: global configs ['rlang=True', 'sourcekit-lsp=False', 'typescript-language-server=False', 'vscode-css=False', 'clangd=False', 'lsp-tsserver=False', 'dart=False', 'ocaml=False', 'bashls=False', 'pyls=False', 'sorbet=False', 'intelephense-ls=False', 'jdtls=False', 'ruby=False', 'erlang-ls=False', 'phpls=False', 'elixir-ls=False', 'gopls=False', 'reason=False', 'javascript-typescript-langserver=False', 'rust-analyzer=False', 'polymer-ide=False', 'flow=False', 'golsp=False', 'rls=False', 'cquery=False', 'haskell-ide-engine=False']
LSP: group 0 view None
LSP: window 2 starting 1 initial views
Package Control: Skipping automatic upgrade, last run at 2020-05-23 16:44:30, next run at 2020-05-23 17:44:30 or after
LSP: window 2 requests rlang for C:\Users\emman\Dropbox\Documents\Teaching\Courses\CPE\Undergrad\Spring 2020\Week 1\Polanyi.Rmd
LSP: starting ['C:\\Program Files\\R\\R-4.0.0\\bin\\x64\\R.exe', '--quiet', '--slave', '-e', 'languageserver::run()']
LSP: window 2 added session rlang
LSP: LSP stream logger stopped.
LSP: process 11236 stdout ended (still alive)
LSP: process 11236 exited with code 1
LSP: transport failed
`

**Comment by randy3k** [comment]
Did you install `languageserver`? It may be the same issue as https://github.com/REditorSupport/sublime-ide-r/issues/42

**Comment by eteitelbaum** [comment]
Yes I think it is the same issue. It is installed but in a library that R-IDE cannot see.
