### ISSUE TITLE
Completion on user-defined functions doesn't work.

### ISSUE THREAD

**Issue by hifall** [REditorSupport/languageserver#27]
While completion on built-in functions like paste seems to work, completion on user-defined functions doesn't seem so.

For example, if I define a function like `addcustom`, and later I enter '`addcu`' expecting `addcustom` to be in the completion candidate list, it's not.

**Comment by randy3k** [comment]
Ya, it is supported in v0.2.4.

**Comment by randy3k** [comment]
Ai, there are actually a few bugs in v0.2.4. Please install the current master and try again.
I will publish another release in a week.

**Comment by hifall** [comment]
So glad to see that this feature will be improved soon.

Awesome stuff! 👍

**Comment by randy3k** [comment]
Actually, I just picked up the development today, langauageserver has not been updated for a while.

**Comment by hifall** [comment]
I see.

I think this project definitely brings much value to many members of the R community. It certainly does to me.

**Comment by hifall** [comment]
Now that 0.2.5 is released, is this supposed to be fixed?

**Comment by shoorlyne** [comment]
I see. I will wait until CRAN is back then.

**Comment by hifall** [comment]
Okay. I will wait until it's on CRAN then.

**Comment by hifall** [comment]
Doesn't seem working for me -- still unable to see a user-defined function appear in the completion list.

**Comment by randy3k** [comment]
It works for me. Note that the server only caches user functions when a file is opened or saved.


<img width="386" alt="screen shot 2018-09-11 at 10 07 23 am" src="https://user-images.githubusercontent.com/1690993/45365437-8548ab00-b5aa-11e8-8d35-4ca2e709fb97.png">

**Comment by hifall** [comment]
I see.

But why this limitation (the server only caches user functions when a file is opened or saved)? Other language servers I have worked on don't require this.

Is it possible to make it in-memory?

**Comment by randy3k** [comment]
It is partly because R is unfortunately too slow. And a more economical reason is to save cpu power. Caching functions on the fly requires a lot of cpu power (related to R being slow). It is particularly important for laptop users.

With that said, it is totally possible to make a setting to allow online caching. I am not a big fan of it and I would still recommend users turning it off, even if it exists, to save battery life.

**Comment by renkun-ken** [comment]
It would be expensive at the moment to cache functions at every key stroke. I'm wondering if it makes sense and if it's possible to cache every N seconds?

**Comment by renkun-ken** [comment]
1e1c74dbf0cf5872cad3f5ce4e49f367dd147530 should fix this.
