### ISSUE TITLE
multi workspaces

### ISSUE THREAD

**Issue by qinwf** [REditorSupport/languageserver#272]
https://github.com/qinwf/demo-multi

<img width="1235" alt="mono" src="https://user-images.githubusercontent.com/7472151/83504684-5baa8280-a4f7-11ea-8262-e890e79b79e5.png">

For an R monorepo with multi R packages, it will be better to separate the workspace for completion.

For example, when I open [wch/r-source](https://github.com/wch/r-source) monorepo, and it will contain multiple R packages. 

When I am editing inside one package, the completion should reflect the current package namespace.

**Comment by renkun-ken** [comment]
The `workspaceFolders` in initialization config must be respected to work with multi-root workspace, which is a non-trivial change where we need to either setup a `Workspace` for each workspace folder, or take workspace folder of the requests into account.

**Comment by randy3k** [comment]
I have been slowly refactoring the codebase to support workspace in previous commits. It still require some work to support multi workspace.

**Comment by qinwf** [comment]
For `multi R package folders` and `single VS Code workspace` project:

I am thinking about adding a new R6 class `Workspaces`

```r
on_initialize <- function(self, id, params) {
    logger$info("initialization config: ", params)
    self$processId <- params$processId
    self$rootUri <- params$rootUri
    self$rootPath <- path_from_uri(self$rootUri)

    - self$workspace <- Workspace$new(self$rootPath)

    ---------
    # scan for sub workspaces
    + self$workspaces <- Workspaces$new(self$rootPath)

    self$initializationOptions <- params$initializationOptions
    self$ClientCapabilities <- params$capabilities
    ServerCapabilities <- merge_list(
        ServerCapabilities,
        getOption("languageserver.server_capabilities"))
    self$deliver(Response$new(id = id, result = list(capabilities = ServerCapabilities)))
}
```


```r
#' `textDocument/completion` request handler
#'
#' Handler to the `textDocument/completion` [Request].
#' @keywords internal
text_document_completion  <- function(self, id, params) {
    textDocument <- params$textDocument
    uri <- textDocument$uri

    - document <- self$workspace$documents$get(uri)

    --------------

    + workspace <- self$workspaces$get(uri)
    + document <- workspace$documents$get(uri)

    point <- document$from_lsp_position(params$position)
    self$deliver(completion_reply(id, uri, self$workspace, document, point,
        self$ClientCapabilities$textDocument$completion))
}
```

But these changes do not handle `multi R package folders` and `multi VS Code workspaces`.

I just knew about `workspaceFolders` option inside the LSP.

**Comment by renkun-ken** [comment]
It might not seem easy to respect `.Rprofile` in each workspace to support e.g. separate `renv` where different sets of packages are installed. I'm wondering if we could start a languageserver from each workspace folder and send request to the corresponding languageserver?
