### ISSUE TITLE
Hover shows on Rmd chunk start line

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#281]
For the following Rmd document, hover should not show on the chunk start line.

````
```{r chunk-2, eval=TRUE}
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)

fun3 <- function(x, y) {
  x + y
}
```
````

<img width="713" alt="image" src="https://user-images.githubusercontent.com/4662568/85083738-301cdd00-b205-11ea-98c3-c16ec29ad5e9.png">

**Comment by randy3k** [comment]
But I could also see that it is useful to the right hand values after =.
