### ISSUE TITLE
Exclusions in .lintr not working

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#282]
From https://github.com/Ikuyadeu/vscode-R/issues/354.

The `exclusions` in `.lintr` is not working:

`.lintr`:

```
exclusions: list("test1.R")
```

`test1.R`:

```r
1+1
```

The file is still diagnosed, implying that the `exclusions` is not respected.

This is caused by that we lint a temp file with potential unsaved edits rather the original file in the workspace. The exclusions do not apply to the temp file path.

**Comment by randy3k** [comment]
I haven’t tested it. In normal circumstances, would `linter::lint(file)` runs if the file is excluded? I asked it because we run `lint` explicitly.

**Comment by renkun-ken** [comment]
`lintr::lint(file)` omits no result if the file is excluded in `.lintr`.

**Comment by franzbischoff** [comment]
Suggestion, while the bug is not fixed:
write this inside the file
```R
# nolint start
your code
# nolint end
```
