### ISSUE TITLE
On save, lintr raises "unexpected '/'" error

### ISSUE THREAD

**Issue by otherdoug** [REditorSupport/languageserver#283]
### Issue

When saving R script files in Atom, `lintr` called via `languageserver` output reports an error `unexpected '/'` in line 1 regardless of script content.
<img width="687" alt="lintr with unexpected front-slash error" src="https://user-images.githubusercontent.com/53023343/85463199-fb45b880-b56b-11ea-8aca-3d0b81feee34.png">

Otherwise `lintr` output generally works as expected when making inline edits. Further typing without saving runs `lintr` again, and produces accurate results:
<img width="692" alt="lintr with accurate output" src="https://user-images.githubusercontent.com/53023343/85463321-20d2c200-b56c-11ea-82e3-63b3db7d1ce6.png">

### Potential cause

The `unexpected '/'` error appears to come from running `lintr::lint` on a file URI that looks like the text of an R script instead of a path to an R script:
```R
> # File URI string with newline at the end
> lintr::lint('file:///Users/myusername/local/path/to/the/file/deleteme.R\n', linters = NULL)
<text>:1:6: error: unexpected '/'
file:///Users/myusername/local/path/to/the/file/deleteme.R

> # File path
> lintr::lint('/Users/myusername/local/path/to/the/file/deleteme.R', linters = NULL)
/Users/myusername/local/path/to/the/file/deleteme.R:5:1: style: Lines should not be more than 80 characters.
tmp <- "This string is so long that it should raise a linter info message, but it won't."
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
```

The did-save / text-sync interface appears to be origin. The interface stores the file URI in `params$textDocument` and stores what I assume is the document content in `params$text` though I have not been able to devise an example that actually stores anything there.
https://github.com/REditorSupport/languageserver/blob/61259eb9d789bdc2be7f13e4cf19ff209d5feec3/R/interfaces.R#L378-L386

When `text_document_did_save(...)` is called, `params$text` partial matches with `params$textDocument` when `params$text` is undefined. This causes `content` to populate from `stringi::stri_split_lines(text)[[1]]` by splitting the file URI as text, rather than loading the file URI from the path `stringi::stri_read_lines(path)`.
https://github.com/REditorSupport/languageserver/blob/61259eb9d789bdc2be7f13e4cf19ff209d5feec3/R/handlers-textsync.R#L63-L85

When `lintr::lint` is eventually called on `content` in `diagnose_file(...)` we get the `unexpected '/'` error because a file URI like `file:///blah...` isn't valid R syntax, and the unexpected forward-slash is where that's detected.
https://github.com/REditorSupport/languageserver/blob/61259eb9d789bdc2be7f13e4cf19ff209d5feec3/R/diagnostics.R#L95-L97

### Attempted fixes
I've made a hacky substitution of `textContent` for `text` in the two blocks above to avoid partial-matching `text` with `textDocument` and it appears to resolve the issue. However, I'll be the first to admit I'm not familiar with the `languageserver` interface, so I don't know what else may be expecting `param$text` to exist.
```R
did_save_text_document_params <- function(uri, text) { 
   structure( 
     list( 
       textDocument   = uri, 
       textContent    = text 
     ), 
     class = "did_save_text_document_params" 
   ) 
 } 
```
```R
text_document_did_save <- function(self, params) { 
     textDocument <- params$textDocument 
     text <- params$textContent 
     uri <- uri_escape_unicode(textDocument$uri) 
     logger$info("did save:", list(uri = uri)) 

   . . . 
}
```

Looking at the surrounding code in `textsync.R`, I also notice that `text_document_did_open` uses `text <- textDocument$text` to populate `text`, rather than `text <- params$text`. Perhaps someone more familiar with the spec may be able to say whether this difference is intentional or accidental.
https://github.com/REditorSupport/languageserver/blob/61259eb9d789bdc2be7f13e4cf19ff209d5feec3/R/handlers-textsync.R#L5-L10

### Environment details
I am using Atom 1.48.0 with packages:
* atom-ide-ui
* atom-language-r
* ide-r

### Potentially related issues
#250 -- looks like the same lintr error output

**Comment by randy3k** [comment]
Would you report the debug log from Atom?

Open the console, run `atom.config.set('core.debugLSP', true)` and restarting atom.
You should then able to see the debug log on the console.

**Comment by otherdoug** [comment]
Here you go: [atom_debug.log](https://github.com/REditorSupport/languageserver/files/4822412/atom_debug.log)

That's opening Atom, saving the file, modifying the file, saving the file again.

Please let me know if I've missed anything, or if anything else would be helpful.

**Comment by renkun-ken** [comment]
A simple fix is to use `[["text"]]` instead of `$text` to avoid partial matching in this case, or we should make sure both element exist in the list in the first place.

**Comment by renkun-ken** [comment]
Maybe we should go through all these interfaces and see if there are potential risks of partial matching in other places.

**Comment by randy3k** [comment]
How about switching to https://rdrr.io/cran/xfun/man/strict_list.html? Though I don't know if there will be some overheads.

**Comment by randy3k** [comment]
I guess `textDocument[["text"]]` should be an easier solution. @otherdoug Thank you for diving into the cause.

**Comment by renkun-ken** [comment]
Somewhere in the R documentation suggests that `$` is only recommeded for interactive use and `[[x]]` for programmatic use where there's no partial matching.

**Comment by renkun-ken** [comment]
I go through all the interfaces and `did_save_text_document_params` is the only one partial match could happen.

**Comment by renkun-ken** [comment]
@otherdoug Are you interested in putting up a PR? New contributors are always welcome!

**Comment by otherdoug** [comment]
Sure—I should be able put something together this weekend.
