### ISSUE TITLE
Show function parameters at the top of the autocompletion

### ISSUE THREAD

**Issue by strboul** [REditorSupport/languageserver#285]
I believe it'll be much better if the function parameters are displayed at the top of the suggested completions when the cursor is inside a call.

Example screenshot:

![rlanguageserver](https://user-images.githubusercontent.com/25015317/85880086-bcb63500-b7db-11ea-8705-2db5fc6b0384.png)

*`decreasing` can appear as the first*

Thanks a lot for the languageserver :heart:

**Comment by randy3k** [comment]
IIRC, the protocol has nothing to control the order.

**Comment by renkun-ken** [comment]
In https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion, is `CompletionItem.sortText` the property that determines the order of items in the completion list?

**Comment by randy3k** [comment]
Oh, you are right. Did notice this one.

**Comment by strboul** [comment]
I confirm that's working 🎉
