### ISSUE TITLE
Specifying default linters in .Rprofile doesn't work anymore

### ISSUE THREAD

**Issue by hermidalc** [REditorSupport/languageserver#29]
My default linters specification in .Rprofile doesn't work anymore.  Not sure what upgrade or otherwise caused it to stop working.  I do not have a .lintr file.  I set a longer line length and suppressing infix spaces warning:

```R
setHook(
    packageEvent("languageserver", "onLoad"),
    function(...) {
        options(languageserver.default_linters = lintr::with_defaults(
            line_length_linter=lintr::line_length_linter(120),
            object_usage_linter=NULL,
            object_length_linter=NULL,
            object_name_linter=NULL,
            commented_code_linter=NULL,
            infix_spaces_linter=NULL
        ))
    }
)
```
I'm using R 3.4.3, languageserver 0.2.5, Atom 1.33.1 with ide-r 0.1.8.  When I have files open in Atom it gives me line length and infix spaces warnings.  It used to work not sure why it stopped.

**Comment by randy3k** [comment]
A new version was released last month. I’ll need to see if it breaks anything. It has been working for me for a while though

**Comment by hermidalc** [comment]
I feel a bit blind as to what is going on under the hood, is there a way to check if languageserver is actually loading and applying the default linters?

**Comment by randy3k** [comment]
Unfortunately, it is not possible to peek into the internal logic. You could try
```r
languageserver:::diagnose_file(<the file you want to lint>)
```
to see if it report infix spaces errors.

**Comment by hermidalc** [comment]
Hi - thank you I figured it out finally after your help.  I'm using Atom in IDE mode so it was using lintr from the ide-r package plus I accidentally had the non-IDE linter-lintr package installed as well.  The redundant second package was not looking at the .Rprofile languageserver custom settings.  I uninstalled linter-lintr and then everything is better.
