### ISSUE TITLE
bookdown support

### ISSUE THREAD

**Issue by inventionate** [REditorSupport/languageserver#290]
Are there any plans or a preferred approach when using bookdown? Here, typically all loaded packages are contained in an index.rmd file. The following chapters are then divided into several files, which is why auto-completion unfortunately does not work. Is it possible to always parse the index.rmd and a "setup" named code chunk automatically?

**Comment by renkun-ken** [comment]
How is `index.rmd` related with other rmarkdown files?

From https://github.com/rstudio/bookdown-demo, it seems there's no explicit code in The Rmd files to relate to each other. Different from what #20 suggests where `source(file)` could be caputured to extend completion, these Rmd files appear to be more independent in code but relie on how bookdown compiles them.

Currently, all open R/Rmd files share the same workspace that provides workspace completion. You might need to open `index.rmd` while you are editing other Rmd files if you want to share the same packages being attached to provide the same set of workspace completion.

**Comment by inventionate** [comment]
Many thanks for the fast answer! Unfortunately this is true, there is no direct reference in the Rmd chapter files. Bookdown does the merging while rendering. Only the names of the files are predefined. Maybe you can go over them? Otherwise I use the workaround with manually opening the index.Rmd file. Thanks for the hint and the great package!

**Comment by inventionate** [comment]
I understand that and I think it is good if the package does not become too complex. 

Still an idea though, are there any plans to manually set the default loaded packages for a session via the configuration file? I use Vim and so I could load the needed packages by default, depending on the project and independent of the files. Maybe this is a flexibel approach for similar setups.

**Comment by renkun-ken** [comment]
This is already possible if you are using the latest vscode-r-lsp as the language server is started from the project folder. You could put the following `.Rprofile` in your project folder:

```r
if (file.exists("~/.Rprofile")) {
  source("~/.Rprofile")
}

library(pkg1)
library(pkg2)
```

Then the language server started from the project folder will respect this profile and load these packages on startup.

**Comment by randy3k** [comment]
I think OP wanted to load an arbitrary package into the workspace so language features such as completion would work for that package. Putting the packages into `.Rprofile` won't do that.

**Comment by renkun-ken** [comment]
>I think OP wanted to load an arbitrary package into the workspace so language features such as completion would work for that package. Putting the packages into .Rprofile won't do that.

I don't quite understand. Latest languageserver respects the project profile as the following to resolve startup packages https://github.com/REditorSupport/languageserver/pull/302/files#diff-68a7107742aa2f6260d5e64b12b9ca1cR32-R40

Then packages attached in `.Rprofile` will be loaded in languageserver workspace by default and `resolve_task` session is started from project folder too and will find these packages are attached so completions are provided. Maybe I misunderstand something?

**Comment by randy3k** [comment]
Oh, you are right. I have completely forgotten about #302. Thank you for the clarification.

**Comment by inventionate** [comment]
Much obliged! This is exactly what I was looking for. Unfortunately the https://github.com/neoclide/coc-r-lsp version doesn't seem to be updated (I use Neovim), so the feature doesn't work for me yet.

**Comment by renkun-ken** [comment]
Closing for now.
