### ISSUE TITLE
Highlight user defined function

### ISSUE THREAD

**Issue by MrJGao** [REditorSupport/languageserver#298]
Is there any plan for this feature? Just want to distinguish customized functions from system/library functions. Thanks

**Comment by randy3k** [comment]
Syntax highlight is not the duty of language sever. You will need to consult your editor related packages. 

I may point you to the right repo if you tell us what editor you are using.

**Comment by MrJGao** [comment]
Thank you @randy3k , I'm using VS Code.

**Comment by randy3k** [comment]
You may transfer the issue at https://github.com/Ikuyadeu/vscode-R

**Comment by MrJGao** [comment]
Thank you very much. I'll close this.
