### ISSUE TITLE
How to sync with language-client neovim?

### ISSUE THREAD

**Issue by beigebrucewayne** [REditorSupport/languageserver#3]
typically it goes as follows within my (.vimrc / init.vim):

let g:LanguageClient_serverCommands = {
  \ 'python': ['pyls'],
  \ 'go': ['go-langserver'] }

However, I'm not sure how to set this up for this version. I tried the following:

'r': ['languageserver'] and library(languageserver)

but no luck, what am I missing?

https://github.com/autozimu/LanguageClient-neovim

**Comment by randy3k** [comment]
You need to install the development version of languageserver

```
devtools::install_github("REditorSupport/languageserver")
```
and use  command 
```
R --quiet --slave -e 'languageserver::run()'
```
listed in [README](https://github.com/REditorSupport/languageserver#languageserver-an-implementation-of-the-language-server-protocol-for-r) to launch the server.

However, it is still working in progress, it may not work

**Comment by beigebrucewayne** [comment]
That's exactly what I did, but no luck. Usually completion syncs with nvim-completion-manager out of the box. Either way, appreciate the effort! Definitely will keep an eye out.

**Comment by randy3k** [comment]
It runs for me

![screen shot 2017-12-08 at 12 29 19 pm](https://user-images.githubusercontent.com/1690993/33777606-81d66fa0-dc13-11e7-9e9e-76b0b1e3af68.png)

```
let g:LanguageClient_serverCommands = {
    \ 'r': ['R', '--quiet', '--slave', '-e', 'languageserver::run()'],
    \ }
```

However, please note that languageserver is still very buggy and may not work as expected.

**Comment by beigebrucewayne** [comment]
Ah-ha, I see my error now. Thank you!

**Comment by randy3k** [comment]
Be aware that it now only supports completions and linting.

**Comment by beigebrucewayne** [comment]
Those were my main two desires for wanting it in the first place. So, I'm a happy camper! Thanks again!

**Comment by randy3k** [comment]
It seems that after I did `:cq`, the R process was not killed and ran at 100% cpu.

**Comment by randy3k** [comment]
The 100% cpu load should be fixed https://github.com/REditorSupport/languageserver/commit/b93e6a975a6ab48f038b3abedfe31ec1a39c28a5

**Comment by beigebrucewayne** [comment]
The battle rages on! I'll be sure to pop in if I catch anything else worth noting.

**Comment by randy3k** [comment]
d562184 fixes it.
