### ISSUE TITLE
Roxygen example code messes up documentation

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#304]
Currently, the workspace documentation is simply the uncommented text of comment above a symbol. This works if the comment is written in markdown, but it does not work well with content in roxygen `@examples` tag where R code is supplied.

For example, the following code

```r
#' Session Pool with Many R Sessions
#'
#' @examples
#' \dontrun{
#' # create 3 cached r sessions in the pool
#' pool_size <- 3
#' pool_name <- "common"
#' pool <- SessionPool$new(pool_size, pool_name)
#'
#' # check idle_size before acquiring session
#' n <- pool$get_idle_size()
#'
#' # if there are idle sessions, acquire session
#' session <- pool$acquire()
#'
#' # check session is not null and then use session
#' is.null(session)
#'
#' # use session
#' # please read R6 Class `Session` documentation
#'
#' }
#' @keywords internal
SessionPool <- R6::R6Class("SessionPool", ...)
```

its documentation is presented in hover like

![image](https://user-images.githubusercontent.com/4662568/86703553-93e93780-c046-11ea-979f-c6cf0edd3591.png)

If we could recognize the code part and use markdown code chunk to enclose it and it would certainly look better.

**Comment by randy3k** [comment]
`roxygen2::parse_text` may be useful in this case.

```
roxygen2::parse_text("#' Title\n#'\n#' @examples\n#' \\dotrun{\n#' }\nfoo", env = NULL)
```

**Comment by renkun-ken** [comment]
Yes, I'm trying with this.

**Comment by renkun-ken** [comment]
Do you think we need a hard dependency on `roxygen2`? It seems that we could use `roxygen2` when it is installed and not use it if not.

**Comment by randy3k** [comment]
It sounds reasonable to me.

**Comment by randy3k** [comment]
I didn't some quick investigation. `roxygen2` is actually not that bad.

```
r$> pdb <- available.packages()

r$> lsver = sort(tools::package_dependencies("languageserver", db = pdb, recursive = TRUE)[[1]])

r$> roxygen2 = sort(tools::package_dependencies("roxygen2", db = pdb, recursive = TRUE)[[1]])

r$> setdiff(roxygen2, lsver)
[1] "brew"       "commonmark" "Rcpp"
``

**Comment by renkun-ken** [comment]
Thanks for the investigation! Do you prefer depending on `roxygen2`?

Another question, do we only show a simple description of the object like in signature/completion resolve, and show argument description in completion resolve, to be consistent with the current documentation list structure `list(title, description, arguments = list())`?

```r
#' Session Pool with Many R Sessions
#'
#' This is a description of the function.
#'
#' @param var1 variable 1
#' @param var2 variable 2
#' @return a new object
#' @export
#' @importFrom data.table fread
#' @examples
#' \dontrun{
#' # create 3 cached r sessions in the pool
#' pool_size <- 3
#' pool_name <- "common"
#' pool <- SessionPool$new(pool_size, pool_name)
#'
#' # check idle_size before acquiring session
#' n <- pool$get_idle_size()
#'
#' # if there are idle sessions, acquire session
#' session <- pool$acquire()
#'
#' # check session is not null and then use session
#' is.null(session)
#'
#' # use session
#' # please read R6 Class `Session` documentation
#' }
#' @keywords internal
fun <- function(var1, var2) {
  var1 + var2
}
```

![image](https://user-images.githubusercontent.com/4662568/86720170-57720780-c057-11ea-96cc-029cfd823981.png)

![image](https://user-images.githubusercontent.com/4662568/86720267-6f498b80-c057-11ea-9309-d49fd91d8c78.png)

![image](https://user-images.githubusercontent.com/4662568/86720233-68227d80-c057-11ea-8ad9-66b94ed16eed.png)

![image](https://user-images.githubusercontent.com/4662568/86720301-77a1c680-c057-11ea-9eca-b55034cd12c0.png)

or we show as much information as possible directly in hover? In this case, we have to deal with certain code tags such as `@examples`.

**Comment by randy3k** [comment]
Hovering is a bit different from the completion items and it is a way to query more information about an interested subject. I think all relevant information should be shown in such cases.

**Comment by renkun-ken** [comment]
OK, then it would look more like the help documentation shown in hover. I'll try to make hover more informative.

**Comment by randy3k** [comment]
By the way, I am fine with either depending `roxygen2` explicitly or `requireNamespace("roxygen2", quietly = TRUE)`.

**Comment by randy3k** [comment]
thank you for working on it.
