### ISSUE TITLE
Cannot disable lintr

### ISSUE THREAD

**Issue by JohnCoene** [REditorSupport/languageserver#315]
I cannot disable the linting.

```json
"r.lsp.diagnostics": false
```

It's set to `false` but still runs, my screen is covered in these warnings.

**Comment by renkun-ken** [comment]
Thanks for reporting! Confirmed.

**Comment by randy3k** [comment]
I haven’t checked. Is it an issue specific to vscode? @renkun-ken

**Comment by renkun-ken** [comment]
I put some logging and it looks like `workspace/didChangeConfiguration` handler is not called at all with latest vscode.

**Comment by renkun-ken** [comment]
This looks like an issue caused by the recent changes in vscode-r-lsp with multi-workspace support. I revert to old vscode-r-lsp and `workspace_did_change_configuration` is called and everything behaves as expected.

I'll take a closer look into this and work out a fix.

**Comment by renkun-ken** [comment]
This is caused by the removal of the `synchronize` options for the language client in vscode-r-lsp:

```json
synchronize: {
            // Synchronize the setting section 'r' to the server
            configurationSection: 'r.lsp',
        }
```

In fact, this options is deprecated:

> (property) SynchronizeOptions.configurationSection?: string | string[]
> The configuration sections to synchronize. Pushing settings from the client to the server is deprecated in favour of the new pull model that allows servers to query settings scoped on resources. In this model the client can only deliver an empty change event since the actually setting value can vary on the provided resource scope.
> 
> @deprecated — Use the new pull model (workspace/configuration request)

I'll add this option back and see if we could adapt to the recommended pull model in future.

**Comment by renkun-ken** [comment]
@JohnCoene Please upgrade your vscode-r-lsp to the latest release and it should work now.
