### ISSUE TITLE
hidden .functions() not auto-completing etc.

### ISSUE THREAD

**Issue by assignUser** [REditorSupport/languageserver#321]
Hello!

I am not sure if this is an intentional decision or an implementation issue but compared to rstudio r-lsp treats hidden functions differently.
In rstudio hidden (internal) functions that are in an .R file will still be auto-completed and their parameters shown etc.
```r
#' An internal function
#' @param x numeric
#' @return x decremented by 1
#' @noRd
.internal <- function(x){
    x - 1
}
```
![image](https://user-images.githubusercontent.com/16141871/90179923-85610f00-ddae-11ea-97c8-3d6e7137c706.png)

In vsc `.internal()` will not be autocompleted, the definition/signature won't show up on hover and it will trip the object_usage lintr:
![image](https://user-images.githubusercontent.com/16141871/90179884-711d1200-ddae-11ea-9f4a-8d5000a0e795.png)

It would be great if hidden functions could also profit from the nice features vsc-r provides. (hidden variables are not affected as far as I can see)
Thank you for your work!

**Comment by randy3k** [comment]
Could you try the development version of languageserver? I remember that @renkun-ken has done something on it.

**Comment by renkun-ken** [comment]
The latest development version already supports functions starting with `.`.

**Comment by assignUser** [comment]
Thank you! Yes it works :) but the object_usage_linter still trips over it:
![image](https://user-images.githubusercontent.com/16141871/90234865-aa8e6580-de20-11ea-9216-01f52c1df892.png)
Which I thought was weird.  So I created a test package using the same .lintr file: https://github.com/assignUser/objectNa where everything works as intended and the linter does not trigger:
![image](https://user-images.githubusercontent.com/16141871/90235033-ed503d80-de20-11ea-9bbc-6a2be7a8bdb1.png)
Maybe it is something in my other project? Some internal functions are not commented with roxygen comments but normal comments, could this be the issue?

**Comment by renkun-ken** [comment]
@assignUser The lintr issue looks like https://github.com/jimhester/lintr/issues/482.

**Comment by assignUser** [comment]
@renkun-ken hmm but why would it not be consistent in both cases?  Well, I guess if its a bug...

**Comment by assignUser** [comment]
The development version of lsp works great, so I'm closing this. Thanks again 😍
