### ISSUE TITLE
Emacs config

### ISSUE THREAD

**Issue by zauster** [REditorSupport/languageserver#33]
The lsp-mode configuration might have changed recently. The current configuration as stated in the README results for me in a "Symbol's function definition is void: lsp-define-stdio-client".

The README for [lsp-mode](https://github.com/emacs-lsp/lsp-mode#adding-support-for-languages) states another snippet for setting up a language support, which would for R be then like this:

```lisp
    (lsp-register-client
     (make-lsp-client :new-connection
                      (lsp-stdio-connection '("R" "--slave" "-e"
                                              "languageserver::run()"))
                      :major-modes '(ess-r-mode inferior-ess-r-mode)
                      :server-id 'lsp-R))
```
I've tested this, works fine for me

**Comment by randy3k** [comment]
Thanks.

**Comment by randy3k** [comment]
Updated
