### ISSUE TITLE
How to stop changing "=" to "<-" when formatting the document

### ISSUE THREAD

**Issue by albert-ying** [REditorSupport/languageserver#333]
Wondering is there a way to customize the default assigning operator for formating.

**Comment by renkun-ken** [comment]
See https://github.com/REditorSupport/languageserver#customizing-formatting-style.

You could tweak the default styler by adding the following option in your `.Rprofile`:

```r
options(languageserver.formatting_style = function(options) {
    style <- styler::tidyverse_style(indent_by = options$tabSize)
    style$token$force_assignment_op <- NULL
    style
})
```
