### ISSUE TITLE
Folding ranges based on outline sections

### ISSUE THREAD

**Issue by albert-ying** [REditorSupport/languageserver#334]
Hi! I'm wondering is there a way to fold regions based on sections in VScode, which is supported in RStudio by default:

![image](https://user-images.githubusercontent.com/59846322/92986605-3203de80-f48a-11ea-9087-fdc6da6228ae.png)

I'm pretty sure there is an easy way to do it since we can fold sessions in .Rmd files in vscode.

**Comment by renkun-ken** [comment]
Folding ranges based on outline sections is already supported in dev version. Please try installing the latest development version and see if it works for you.
