### ISSUE TITLE
Implement referencesProvider

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#336]
>The references request is sent from the client to the server to resolve project-wide references for the symbol denoted by the given text document position.

The [referencesProvider](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references) could be implemented to have the following behavior:

1. If the workspace is an R package, then find references in all R documents; otherwise, find references in open documents.
2. Get the token at the requested position.
3. Use the approach of definition provider to find definition of the token.
4. Find all symbols in the documents and go-to-definition of each symbol.
5. All symbols that go to the same definition will be included as a reference of the original token.

**Comment by randy3k** [comment]
It sounds a valid approach. :+1
