### ISSUE TITLE
Go to Definition

### ISSUE THREAD

**Issue by andycraig** [REditorSupport/languageserver#34]
It seems like there is some interest in Go to Definition lately (e.g., https://github.com/Ikuyadeu/vscode-R/issues/105) so I thought I'd open an Issue for it.

To me it looks like the way you'd go about implementing it would be to have `workspace_sync` grab the function definitions in the documents and store their locations. This would be done either by modifying `parse_document` or creating a similar function. To look up the location of a requested definition, you'd use a function that would be structured like `get_signature`.

Functions with the same name can be declared more than once in R; in these cases, I think provided Go to Definition goes to one of the definitions it would be okay.

Conceivably you could have Go to Definition work for variables as well as functions but since they're more likely to be mutated I don't think it's worth including them at this point.

@randy3k How does the above sound to you? I thought I might have a try at implementing it if no-one else  is working on it. (@minkir014 @Tutuchan If you're working on this already let me know - I'd be happy to leave it to someone else!)

**Comment by minkir014** [comment]
functions with same name can't be declared in the same class.

**Comment by randy3k** [comment]
You are correct, we will need to modify `parse_document` to capture the symbols and definitions. You will be appreciated to work on this. I personally won’t have time in the following two months to work on this project.

**Comment by Tutuchan** [comment]
I started working on this (see [here](https://github.com/Tutuchan/languageserver/tree/definition)) some time ago but did not actually finish the implementation, maybe you can take a look.

**Comment by minkir014** [comment]
To what extent the last commit you did about go to definition made go to definition works?

**Comment by minkir014** [comment]
@Tutuchan Where are you?

**Comment by Tutuchan** [comment]
I'm busy.

I remember it working fairly well in VSCode for definition of functions in packages, not for functions in the current environment.

**Comment by andycraig** [comment]
@Tutuchan Oh wow, you’ve implemented most of this already! If this is something you were hoping to come back to soon let me know and I’ll leave it for you to finish. For now, I’ll start from your fork and have a look at how to modify `parse_document`.

**Comment by Tutuchan** [comment]
@andycraig, I was hoping to come back to it someday but I'm not doing much R work these days so it is very low on my list of priorities. If you want to go for it, please do !
