### ISSUE TITLE
When closing a file, "Problems" should be removed

### ISSUE THREAD

**Issue by bersbersbers** [REditorSupport/languageserver#348]
I constantly see linting messages from files which I have already closed. Since there is no way to delete them, I feel it would be sensible to remove them when the file is closed.

See also https://github.com/Ikuyadeu/vscode-R/issues/376#issuecomment-650915755, https://github.com/REditorSupport/languageserver/pull/292, https://github.com/microsoft/vscode-python/issues/12630, https://github.com/microsoft/vscode/issues/101885, https://github.com/microsoft/vscode/issues/100646

**Comment by renkun-ken** [comment]
Currently, the diagnostics is only removed when an external file (outside the workspace root) is closed.

The languageserver will load all R files in `./R` if the workspace is a package. Does it make sense to you that if the workspace is not a package, then closing a file should remove its diagnostics while if the workspace is a package then closing a file does not remove its diagnostics?

**Comment by bersbersbers** [comment]
> Does it make sense to you that if the workspace is not a package, then closing a file should remove its diagnostics

Yes, for the reasons outlined above: it is how most other extensions operate, and once you delete a file, you are stuck with its "Problems" forever.

> while if the workspace is a package then closing a file does not remove its diagnostics

I am not working with packages, so I can give useful comments only on the non-packages situation. Having said that: I can see how one should have a more holistic view of one's code in this situation: for example, because packages are often shared publicly or even published in repos which have stricter linting requirements that the average coder's collection of scripts. So I would consider this reasonable. But again, my exposure to this situation is pretty much null.

**Comment by renkun-ken** [comment]
OK, then #349 should work for you. For non-package workspace, when you close a file, it will remove its diagnostics. When you delete the file, the text editor is not necessarily closed. When you close its editor, then its diagnostics will be removed too. Does this sound reasonble to you?

**Comment by bersbersbers** [comment]
> When you delete the file, the text editor is not necessarily closed. 

Good point.

> When you close its editor, then its diagnostics will be removed too. Does this sound reasonable to you?

Yes, it does.

**Comment by renkun-ken** [comment]
You could install the latest development version and see if it works for you.
