### ISSUE TITLE
[vscode] Arguments not shown correctly in function hover

### ISSUE THREAD

**Issue by ManuelHentschel** [REditorSupport/languageserver#352]
When hovering over a function, the list of arguments is often formatted as normal text instead of code, leading to a very wide hover box and hard to read argument description.

![Capture1](https://user-images.githubusercontent.com/53863351/97476027-3f97f980-194e-11eb-9e2f-6d3874f6fbcb.PNG)
![Capture2](https://user-images.githubusercontent.com/53863351/97476034-40309000-194e-11eb-98e1-0e5d09c4da58.PNG)
![Capture3](https://user-images.githubusercontent.com/53863351/97476036-40c92680-194e-11eb-901b-2e4efa044052.PNG)

**Comment by renkun-ken** [comment]
The documentation shown in hover is basically obtained from the following:

```r
enc2utf8(repr::repr_text(utils::help("get")))
```

which is not markdown but plain text. VSCode tries to present the text in R language somehow.

I'm not sure if we have a robust way to convert the help documentation to Markdown format. If it is possible, it would certainly resolve this issue.

**Comment by randy3k** [comment]
I guess we will need to wait until `repr` supports [markdown](https://github.com/IRkernel/repr/blob/7b0a0987ac9850bea9a2c8fb259f4bc1ffd48427/R/repr_help_files_with_topic.r#L75).

**Comment by ManuelHentschel** [comment]
Ah ok, thanks for the quick reply anyways!

Are there any possibilities to limit the width of the hovers, without changing the format of the text?

This would already be an improvement and hopefully wouldn't require as much effort (ideally just a hover option `maxWidth` etc.?)

**Comment by renkun-ken** [comment]
The hover seems to auto-adjust with your screen width.

The latest vscode insider already supports sizable completion list but not hover window yet. In fact, it is already requested at https://github.com/microsoft/vscode/issues/14165 and https://github.com/microsoft/vscode/issues/56525.

**Comment by ManuelHentschel** [comment]
Ok Thanks! Then I will close this for now and patiently wait for those updates :)
