### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#355]
Since some new features have been added since last release for a while, are we planning to publish a new release?

@randy3k

**Comment by randy3k** [comment]
Of course. Let me tag a release tonight.

**Comment by randy3k** [comment]
submitted, waiting for cran check.

**Comment by randy3k** [comment]
Released.

**Comment by renkun-ken** [comment]
Thanks!

Looks like NEWS is missing?

**Comment by randy3k** [comment]
Oops. Forgot to update NEWS. By the way. There is an error on Solaris check https://cran.r-project.org/web/checks/check_results_languageserver.html I will need to dive into it.
