### ISSUE TITLE
R language server is submitted as a job on a cluster and retrurn errors 

### ISSUE THREAD

**Issue by liutiming** [REditorSupport/languageserver#356]
```
R Language Server (31591) started
dynamic/: Bad host name, host group name or cluster name

<<Waiting for dispatch ...>>

<<Starting on node-12-2-3>>

R Language Server (31591) exited with exit code 1
```

The cluster system is LSF. The error appears when first remote-ssh in without even opening R (but the file editor has .R script open)

Thanks for this awesome tool!

**Comment by randy3k** [comment]
Could you explain a little more how you launched the job?

**Comment by liutiming** [comment]
I did not launch the job... it was launched by vscode. The error could happen when I open a vscode remote directory and a R file. Sometimes the vscode terminal automatically switch to output panel for R language server and show the error.

**Comment by liutiming** [comment]
OK I think the issue is probably because the system R triggers job submission when it is initiated. I did not realise this as I was in a conda env.
