### ISSUE TITLE
languageserver was removed from the CRAN repository

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#357]
Recently, languageserver is removed from CRAN repo due to the lasting check failures on r-patched-solaris-x86 at https://cran-archive.r-project.org/web/checks/2020/2020-12-16_check_results_languageserver.html.

@randy3k, is there anything we could do about it?

**Comment by randy3k** [comment]
I have just pushed a new release to CRAN, hope that it will work out.

**Comment by rpodcast** [comment]
This was quite a surprise to me.  I discovered the removal after I had done my [live stream](https://www.youtube.com/watch?v=4wRiPG9LM3o) of using VS-Code with R and Docker containers.  I was bailed out because I had a previous version in my `renv` cache directory!

**Comment by randy3k** [comment]
Let's keep the issue open until the new version is released.

**Comment by renkun-ken** [comment]
Looks like languageserver has been brought back to CRAN now.

**Comment by randy3k** [comment]
Ya

**Comment by dwhdai** [comment]
> This was quite a surprise to me. I discovered the removal after I had done my [live stream](https://www.youtube.com/watch?v=4wRiPG9LM3o) of using VS-Code with R and Docker containers. I was bailed out because I had a previous version in my `renv` cache directory!

What is your workflow for using vscode + languageserver + renv? Does languageserver need to be installed separately in every renv project?
