### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kforner** [REditorSupport/languageserver#36]
Hey,
I find this project really useful and interesting. 
I'd like to contribute, but the licensing terms are unclear to me, there's just a copyright mention. 
Could you please clarify it ?

Thanks,
Karl

**Comment by izahn** [comment]
https://github.com/REditorSupport/languageserver/blob/e12d1f91a831de211488e9fe2dc69d5f934514e6/DESCRIPTION#L10 lists [MIT](https://cran.r-project.org/web/licenses/MIT)

**Comment by kforner** [comment]
Ok thanks!
I suppose it would be good to also put it in the LICENSE file, because on the github homepage of the project, if you click on "View License", you get:
``` 
YEAR: 2018
COPYRIGHT HOLDER: Randy Lai
```
which is unclear.

**Comment by randy3k** [comment]
This is a standard template of CRAN packages. See CRAN policy for details. (On mobile now, it should be easy to google it)

**Comment by kforner** [comment]
I understand that. Just saying that adding a line : MIT License to the License file could spare you those kind of spurious issues... ;)
