### ISSUE TITLE
[FR] Display promise / active-binding objects in the OUTLINE

### ISSUE THREAD

**Issue by shrektan** [REditorSupport/languageserver#362]
Considering the following test file: 

**test.R**

```r
x <- 1
y <- "a"
z <- function() {
  'hello'
}
delayedAssign("d", 1)
delayedAssign("err", stop("err"))
makeActiveBinding("a1", function() 1, environment())
```

Currently, only `x`, `y` and `z` are displayed in the OUTLINE but `d`, `err` and `a1` don't.

I hope we can have them in the OUTLINE, too.

![image](https://user-images.githubusercontent.com/8368933/103998998-69379180-51d7-11eb-9aab-e435454fe10c.png)

**Comment by ManuelHentschel** [comment]
Some other ways to assign toplevel variables that might be worth considering:

``` r
assign('b', 2)

`<-`('c', 3)

.GlobalEnv$d <- 4

e <<- 5

s <- 'f'
assign(s, 9)

aa <- bb <- 123
```

**Comment by shrektan** [comment]
Yes, but personally I need the `delayedAssign()` version... so I'm going to focus on this first.

It seems that we may just need to handle `delayedAssign()` and `makeActiveBinding()` in `parse_expr()`. 

I'll try to fix this by myself...
