### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by pdimens** [REditorSupport/languageserver#375]
Perhaps this is a new error b/c I haven't seen it in the open/closed issues, but installation fails due to dependency filesize inconsistencies:
```
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  (converted from warning) downloaded length 2060288 != reported length 2484350
Error: Failed to install 'languageserver' from GitHub:
  (converted from warning) download of package ‘testthat’ failed
```

**Comment by renkun-ken** [comment]
It might be caused by that the mirror is in the middle of sync process. You could try it later.

**Comment by pdimens** [comment]
That seemed to be the issue. Thank you!
