### ISSUE TITLE
Bracket colour matching appears to be broken

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/languageserver#377]
Bracket colour matching appears to be broken. 

(apologies if this is an issue for the VScode-R package, I still struggle to tell where issue should be filed)

![image](https://user-images.githubusercontent.com/8447209/106462946-a4ec1100-648e-11eb-992c-0efe2a33188d.png)

I don't get this issue in any other languages other than R which leads me to believe its an R specific language server issue.

**Comment by renkun-ken** [comment]
Syntax highlighting in vscode is provided by vscode-R rather than languageserver. Please report issue there, thanks!
