### ISSUE TITLE
Create pkgdown website for languageserver

### ISSUE THREAD

**Issue by gvelasq** [REditorSupport/languageserver#378]
I'd be happy to propose a PR for a {pkgdown} website, if it would be helpful.

**Comment by randy3k** [comment]
I am not sure it will be very useful as there is only one exported function `run`.

**Comment by renkun-ken** [comment]
Same thinking here. I thought pkgdown website is more useful for users of the package, but languageserver's use is actually language clients from editors...

**Comment by gvelasq** [comment]
Makes sense, @randy3k and @renkun-ken. Thank you for considering. Happy to close the issue.
