### ISSUE TITLE
there is no package called ‘languageserver’ - but it is installed

### ISSUE THREAD

**Issue by dscharalampidis** [REditorSupport/languageserver#380]
Hi,

I am running Archlinux. I have installed R, code, and the R LSP Client extension.
I have configured r.path to /usr/bin/R where my vanilla R is installed.
I have installed the languageserver package in R. I can load it with `library(languageserver)` but when I start code I get this:
```
R Language Server (96486) started
Error in loadNamespace(name) : 
  there is no package called ‘languageserver’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

R Language Server (96486) exited with exit code 1
```
Any help is greatly appreciated!

**Comment by baslat** [comment]
I have the same issue, except on Windows Server 2019, and I no-longer have the R LSP client extension installed as apparently that has been integrated into the core VS Code capabilities.

**Comment by renkun-ken** [comment]
Looks like the R session started from vscode does not have the same library path with an interactive session you started from your terminal.

You may start an R session where you install the languageserver package and print the library paths:

```r
.libPaths()
```

And put the following settings in your vscode `settings.json`:

```json
"r.lsp.args": [
     "-e",
     "writeLines(.libPaths(),'~/lsp.log')"
    ]
```

and find `~/lsp.log` file and see if the library paths are the same.

**Comment by baslat** [comment]
For some reason that's not creating a log file. I'll investigate a bit more tomorrow, however you might be on to something as I do use a non-standard library location.

**Comment by baslat** [comment]
After way too much trouble realising that in Windows `~` can mean different places depending on what's interpreting it, I finally found the log files. Indeed, LSP is only finding the default locations for the library paths. I have tried adding my custom library path to various R profiles and R environs, but haven't managed to find one yet that is read by language server.

Any suggestions on how to direct language server to my custom library path?

**Comment by renkun-ken** [comment]
You could set up an environment variable `R_LIBS_USER` in your computer settings, or put the following in your `~/.Rprofile`:

```r
.libPaths( c( "path/to/your/library" , .libPaths() ) )
```

**Comment by baslat** [comment]
Neither is working for me with language server.

`R_LIBS_USER` in my renviron file is how I normally set my preferred library path, but is not being detected by language server. And I have also tried removing that line, and adding `.libPaths( c( "path/to/your/library" , .libPaths() ) )` to my Rprofile, but also no luck. 

To clarify both methods work in assigning the library path in RStudio or R CLI, just not in langauge server.

**Comment by baslat** [comment]
And 2 minutes later, I get it working! Thank you!

What worked:
- setting the **first line** in my rprofile to `.libPaths(c("path/to/your/library", .libPaths()))`

What did not work:
- setting the Renviron variable `R_LIBS_USER="path/to/your/library"`
- setting any line except the first line in my rprofile to `.libPaths(c("path/to/your/library", .libPaths()))`
- the package `languageserversetup` by itself, or in conjunction with either of the two points above.

And for future troubleshooters, note that below will actually write to `~/Documents/lsp.log`
```
"r.lsp.args": [
     "-e",
     "writeLines(.libPaths(),'~/lsp.log')"
    ]
```

**Comment by renkun-ken** [comment]
> And for future troubleshooters, note that below will actually write to ~/Documents/lsp.log

In Windows, R's `~` will be expanded to `~/Documents` rather than user home folder.

**Comment by renkun-ken** [comment]
@baslat Thanks for digging into it. Glad to know it works for you now.
