### ISSUE TITLE
R Language server remains open after terminal shutdown

### ISSUE THREAD

**Issue by mjdall** [REditorSupport/languageserver#383]
When closing an instance of radian/R, using R language server, R language server won't kill itself.

- VSCode Version: 1.53.2
- VSCode-R Version: v1.6.4
- OS Version: Windows 10.0.17763 Build 17763

Steps to Reproduce:

1. Open radian/R terminal
2. Close radian/R terminal

Without restarting my computer, I end up with this happening:
![image](https://user-images.githubusercontent.com/41932643/109711568-df6ada00-7c03-11eb-9dfb-12cffae81dfc.png)

**Comment by randy3k** [comment]
I believe these are R sessions created by the language server, not radian. What happened if you close VScode?

**Comment by mjdall** [comment]
Ok, closing VScode kills the processes. And yea, except launching a new R/radian instance seems to launch a new R session for RLS each time

**Comment by renkun-ken** [comment]
Launching a new R/radian instance should not launch new language server processes.

In VSCode, language server processes are created when the language client managed by [vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp) meets the cases in https://github.com/REditorSupport/vscode-r-lsp/pull/45.

**Comment by mjdall** [comment]
Ok, that makes sense, and i'm assuming the language server processes will remain open until VSCode is shut down?
