### ISSUE TITLE
Document link should work with limited file extensions or file size

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#391]
Currently, the document link provider will capture all existing file paths in the document to provide links. Some file paths are binary data files (e.g. `*.fst`) rather than source files (`*.R`) or text-data files (e.g. `*.csv`). Accidentally following the link of data binary data file is not useful (the editor cannot handle the file type) or sometimes makes the editor freeze (via remote-ssh).

I think we should use an option to provide links to a limited collection of file extensions. By default, it might include R, csv, log, txt, etc.

**Comment by randy3k** [comment]
It seems reasonable. The only thing that I may add is to allow users to customize the set of file extensions.

**Comment by renkun-ken** [comment]
Or we could limit the file size of a link because there are too many text file types that should be provided a link (e.g. python, matlab, julia, c++ code files). And we could use [Document Color Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#documentLink_resolve) to check the file size so that it could determine if a link should be provided.

**Comment by randy3k** [comment]
Instead of a whitelist, we could have a blacklist of extension. Thought limiting file size seems reasonable.

**Comment by renkun-ken** [comment]
>Instead of a whitelist, we could have a blacklist of extensions, (pdf, jpeg, exe, dll, etc).

It makes sense. However, in vscode, user could associate these extensions with different editor extensions, e.g. vscode-pdf could open pdf in a WebView in vscode, hex editor could view and edit any binary file.

**Comment by renkun-ken** [comment]
I guess we could first avoid supplying a large file to the editor and leave handling different file formats to the editor at the moment.
