### ISSUE TITLE
Is the some interest in supporting unified Debugger Adapter Protocol ?

### ISSUE THREAD

**Issue by PavelSosin** [REditorSupport/languageserver#40]
Question: There is unified [Debugger adapter protocol](https://github.com/microsoft/debug-adapter-protocol) under development based on the same principals as LSP and uses the same communication protocol stack. Is some interest in adoption of DAP by RStudio Cloud edition? What are special requirement for such protocol different from other regular high-level languages?

**Comment by randy3k** [comment]
I cannot speck of the RStudio. Personally I do aware of DAP. I believe it is better to separate DAP from LSP, but the implementation is not immediately obvious and I don’t have enough time to maintain too many projects now.

**Comment by renkun-ken** [comment]
Related: https://github.com/Ikuyadeu/vscode-R/issues/89.

It seems that DAP for R should run an R session with user specified script file, and translate debugging instructions (add/remove breakpoint, continue, step into, etc.) into stdin to R session, and extract code location change in R stdout (e.g. `debug at /path/to/file#line`). And provide symbols and their values in the current debugging context by inspecting the current environment on browser mode.

**Comment by renkun-ken** [comment]
For debugging, please take a look at https://github.com/ManuelHentschel/VSCode-R-Debugger.
