### ISSUE TITLE
Use `styler::style_text(base_indention=)` for `styler > 1.4.0`

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#400]
`base_indention` is supported via https://github.com/r-lib/styler/pull/649 since styler 1.4.0. We may consider using this instead of hacking into the stylers for `styler >= 1.4.0` in the formatting providers.

**Comment by lorenzwalthert** [comment]
Sounds great. Hope we can clear the way for this in https://github.com/r-lib/styler/issues/763.  Also make sure you'll have the minimal version requirement for styler, which will be `> 1.4.0` since I need to fix things first in styler -.-.

**Comment by renkun-ken** [comment]
Thanks @lorenzwalthert, https://github.com/r-lib/styler/pull/764 could fix the issue.

@randy3k Do you think we should import `style > 1.4.0` and only use `base_indention`, or we check `styler > 1.4.0` and only use `base_indention` if supported or otherwise keep the old hacking way?

**Comment by randy3k** [comment]
I think it is fine to require `style >= 1.4.0`. Thanks for working on it.

**Comment by lorenzwalthert** [comment]
Ok, {styler} 1.4.1 is on CRAN, you can proceed 😀. No release for 1 year, two within almost a week -.-

**Comment by renkun-ken** [comment]
@lorenzwalthert Thanks for the quick release!
