### ISSUE TITLE
Case-insensitive and fuzzy match in completion

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#401]
Currently, we use `startsWith()` to filter completion items. It is fast, but it is case-sensitive and does not allow imprecise matches with the first few characters.

Maybe we should allow some fuzziness and case-insensitivity?

**Comment by randy3k** [comment]
I think it makes sense to make some degrees of fuzziness. Do you happen to know an efficient way to do fuzzy matching in R?

**Comment by renkun-ken** [comment]
The easiest is to use built-in `agrep()` but the completion request is sent by the first few or one character on type, any fuzzy matching will result in too many results. The editor (e.g. vscode) already does some fuzzy matching given a list of completion items.

I tried using `grep(ignore.case = TRUE)` to filter the result, and it works quite well and there's no notable drop on performance from the experience.
