### ISSUE TITLE
Completion not working before close parenthesis

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#410]
Consider the following code

```r
fun <- function(x, y, z) {
  paste0(x, y, z)
}

fun("free"|)
```

Inserting `,` at `|` does not trigger the signature help of `fun(x, y, z)`, and typing e.g. `z` does not get any completion item. However, no error is observed from the logging of languageserver. Also, replacing `"free"` to some other strings, the problem might disappear.

**Comment by randy3k** [comment]
It sounds that the issue of detection of string enclosure.

**Comment by renkun-ken** [comment]
I revert #276 and it works as before. Therefore, it is certainly caused by a regression in #276.

**Comment by randy3k** [comment]
Thanks for the investigation. I'll take a look.
