### ISSUE TITLE
query active filename 

### ISSUE THREAD

**Issue by yonicd** [REditorSupport/languageserver#420]
is there a way to query active filename that that the editor is focused on when running script using languagesever similar to the information returned by `rstudioapi::getActiveDocumentContext()`.

I am trying to extend [{whereami}](https://github.com/yonicd/whereami) to use VSC with languageserver and vscDebugger to solve issues such as https://github.com/yonicd/whereami/issues/22

**Comment by renkun-ken** [comment]
It is supported by [vscode-R](https://github.com/Ikuyadeu/vscode-R/wiki/RStudio-addin-support#implemented-functions). languageserver currently only does static analysis. It does not deal with user interactive session at the moment and thus there's no "running script using languagesever", or am I misunderstanding what you mean?

**Comment by yonicd** [comment]
Yes. those are the functions that I am looking for. I can see the functions being loaded in `vsc.R`, do I need to load `vsc.rstudioapi` in `.Rprofile` or somewhere else?

**Comment by yonicd** [comment]
found the answers here https://github.com/Ikuyadeu/vscode-R/issues/439. thanks! closing.
