### ISSUE TITLE
Unexpected empty results from `textDocument/formatting` request

### ISSUE THREAD

**Issue by siegel** [REditorSupport/languageserver#422]
I'm working on a new LSP client, and I've found a case in which the R language server appears to incorrectly(?) return an empty array of textEdits in response to a `textDocument/formatting` request.

In the attached example file, the linter reports many cases of incorrect formatting; however, sending `textDocument/formatting` for the document results in an empty array of textEdits in the reply, and no error reported by the server.

The parameters to the `textDocument/formatting` request look like this:

```
{
    insertFinalNewline = 0;
    insertSpaces = 0;
    tabSize = 4;
    textDocument =     {
        uri = "file:///Users/siegel/Desktop/LSPTest/random.r";
    };
    trimTrailingWhitespace = 0;
}
```

There don't appear to be any other diagnostics or logging reported by the server; it's started using the command: `R --slave -e languageserver::run()`. Are there any other flags I can add to the command line that might add verbose logging output to stderr?

[random.r.zip](https://github.com/REditorSupport/languageserver/files/6409716/random.r.zip)

**Comment by siegel** [comment]
…as is now obvious :-) from the above, my client was failing to wrap the format parameters in an `options` dictionary. In that case, the server evidently decided to do nothing, which on the one hand is certainly legitimate; on the other hand I think an error returned, or some diagnostic logging would have saved a great deal of time. I'll keep this issue open pending your response, but I don't have an especial objection if you choose to close based on "client bug".

**Comment by randy3k** [comment]
If you run `R --slave -e languageserver::run(debug = TRUE) `, you should be able to see the error.

**Comment by siegel** [comment]
@randy3k Thanks for the tip, that is very helpful. Does (or could) the server honor the `trace` initialization parameter? Currently my client sets that value to `verbose`, and having that trigger debugging output would help greatly.

**Comment by randy3k** [comment]
It seems to be a new setting in LSP 3.16, of course, we are happy to honor that.
