### ISSUE TITLE
If load package via pacman::p_load(), the autocompletion will be not able to work well 

### ISSUE THREAD

**Issue by wdiao-zju** [REditorSupport/languageserver#426]
If I load packages via library, autocompletion wokrs very well in vscode. However, If load package via pacman::p_load(), the autocompletion do not work.

**Comment by renkun-ken** [comment]
Related to #257.

**Comment by renkun-ken** [comment]
We unified the function handling in parsing with a list of parser hook functions. Please try the latest dev and tell me if works well for your case.
