### ISSUE TITLE
Autocompletion will double first word in R chunk in RMD

### ISSUE THREAD

**Issue by wdiao-zju** [REditorSupport/languageserver#445]
Autocompletion will double first word in R chunk in RMD. For example, 'as.character' will be 'as.as.character' in R chunk in .Rmd file but work well in .R file.

**Comment by randy3k** [comment]
Which editor are you using?

**Comment by wdiao-zju** [comment]
sorry, editor is Vscode

**Comment by renkun-ken** [comment]
I could reproduce this in vscode. It looks like in Rmd completing any symbol with `.` will cause this problem.

**Comment by randy3k** [comment]
I think it is a vscode issue, see for example https://github.com/REditorSupport/vscode-R/issues/286
