### ISSUE TITLE
If I wrap library call in suppressPackageStartUpLanguages, autocompletion won't work

### ISSUE THREAD

**Issue by TTTPOB** [REditorSupport/languageserver#451]
if I wrap library call in suppressPackageStartUpLanguages, autocompletion won't work
![image](https://user-images.githubusercontent.com/19909103/124855041-ec953c80-dfda-11eb-9251-1095754216a8.png)
![image](https://user-images.githubusercontent.com/19909103/124855073-fdde4900-dfda-11eb-9993-8fe80ed994d8.png)

**Comment by renkun-ken** [comment]
Same as https://github.com/REditorSupport/languageserver/issues/257#issuecomment-630764947.

**Comment by TTTPOB** [comment]
sorry, I didn't see that
