### ISSUE TITLE
workspaces mixed when using in jupyter notebooks

### ISSUE THREAD

**Issue by TTTPOB** [REditorSupport/languageserver#454]
First I thought this may be a jupyter-lsp bug but according to krassowski/jupyterlab-lsp#642, this may be a bug in R languageserver
I installed #452 version

I don't know what information should I provide.

![image](https://user-images.githubusercontent.com/19909103/125104266-c3c29380-e10f-11eb-993c-f76f433f83d8.png)

**Comment by randy3k** [comment]
We are right, we do not support having different workspaces at all. I believe that most clients spawn a new R process for different Windows. But it seems that Jupyter-lsp are reusing the same process R process. I am not sure if we want to fix it or how we should address it.

**Comment by renkun-ken** [comment]
This is exactly what https://github.com/REditorSupport/vscode-r-lsp/pull/45 is trying to solve using multi-server approach.

**Comment by TTTPOB** [comment]
> This is exactly what [REditorSupport/vscode-r-lsp#45](https://github.com/REditorSupport/vscode-r-lsp/pull/45) is trying to solve using multi-server approach.


> We are right, we do not support having different workspaces at all. I believe that most clients spawn a new R process for different workspace (for a definition of workspace suitable for that editor, says Windows for VSCode). But it seems that Jupyter-lsp is reusing the same ~process~ R process for different notebooks. I am not sure if we want to fix it or how we should address it.

hmmm, I think jupyter is runnig multiple R but only one language server is launched by jupyter-lsp, so is this expected behavior in current version?
![image](https://user-images.githubusercontent.com/19909103/125116813-d3e26f00-e11f-11eb-9daf-3241b6e46105.png)

**Comment by randy3k** [comment]
FYI, [Sublime Text LSP](https://github.com/sublimelsp/LSP) also takes a similar [one-server-per-workspacefolder](https://github.com/sublimelsp/LSP/pull/697#issuecomment-559873447) approach.

While it would be lovely to have support of workspaces, but it seems that it only benefits a few users. Also, without supports from the clients and editors, it is difficult to test things.

**Comment by randy3k** [comment]
> hmmm, I think jupyter is runnig multiple R but only one language server is launched by jupyter-lsp, so is this expected behavior in current version?
> ![image](https://user-images.githubusercontent.com/19909103/125116813-d3e26f00-e11f-11eb-9daf-3241b6e46105.png)


Yes, the main process was launched by jupyter-lsp and the rest and helper R sessions for linting etc.

**Comment by TTTPOB** [comment]
thank you for your reply, I am happy with it then :-)

**Comment by randy3k** [comment]
Ai, a quick check with the codebase of jupyterlab-lsp, they also don't support multiple workspace folders. So enabling multiple workspace folders is not a solution for jupyterlab.

We observe such an issue simply because each notebook is treated as an open R file. And of course, in other editors, we would like to have completions from other R files while editing a particular file.
