### ISSUE TITLE
Minimal {styler} version requirement

### ISSUE THREAD

**Issue by lorenzwalthert** [REditorSupport/languageserver#457]
{styler} won't ever bring up interactive prompt to create a cache (as requested by {R.cache}) as of version 1.5.1. For this reason, the corresponding README explanation becomes obsolete if you add a minimal version requirement on {styler} (`1.5.1`), which I suggest to do.
Also see https://github.com/r-lib/styler/pull/819.

**Comment by renkun-ken** [comment]
Looks like the new `R.cache` will by default uses a global cache root path for the user (`~/.cache/R/R.cache`). Then there seems to be no need to mention the cache issue in README at all.

**Comment by lorenzwalthert** [comment]
The difference is that {R.cache} uses a standard location that does not require user permission according to CRAN policies.
