### ISSUE TITLE
Documentation for functions assigned with `=` differs from functions assigned with `<-`

### ISSUE THREAD

**Issue by krassowski** [REditorSupport/languageserver#466]
It seems that definitions for functions are not extracted properly when those are assigned with eq. Is this intended? This has an annoying effect for example when hovering over functions with signatures spread to multiple lines:

![hover-func-r-eq](https://user-images.githubusercontent.com/5832902/128932175-92e46606-1bc2-4058-ac11-8676d37703c8.gif)

**Comment by renkun-ken** [comment]
I could reproduce this. Completion and signature treats `sum_eq` as a function, but hover does not. Let me take a closer look at this.

**Comment by renkun-ken** [comment]
Could you install the PR and check if it works for you?

```r
remotes::install_github("REditorSupport/languageserver#467")
```

**Comment by krassowski** [comment]
This works great, thank you - that was super quick!

**Comment by randy3k** [comment]
> This works great, thank you - that was super quick!

I agree. @renkun-ken is super responsive in bug fixing.
