### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#470]
Inspired by #469, it is likely that could eliminate those dependencies if we only rely on a tiny proportion of the functions provided in the package, or if they are easily replaceable.

For example, I could not find any usage of `desc` (search `desc::`) but we still import it?

**Comment by renkun-ken** [comment]
I go through the imported packages, looks like everything is fine except `desc` is not used at all.

**Comment by renkun-ken** [comment]
Also, I'd like to move `roxygen2` from `Imports` to `Suggests` like `rmarkdown` since 

1. It has quite heavy dependencies.
2. We only use `roxygen2:::parse_text()`.
3. It is optional and more useful for package developers who are very likely to have installed roxygen2.

**Comment by renkun-ken** [comment]
But it looks like most (if not all) dependencies of `roxygen2` also appear in the dependencies of `styler` and `lintr`, then removing `roxygen2` might not help reduce the installation size and time at all.

**Comment by randy3k** [comment]
> But it looks like most (if not all) dependencies of `roxygen2` also appear in the dependencies of `styler` and `lintr`, then removing `roxygen2` might not help reduce the installation size and time at all.

Then I guess we could keep it.

**Comment by lorenzwalthert** [comment]
FWIW: Also note that {lintr} undergoes a dependency cut: https://github.com/r-lib/lintr/issues/861
