### ISSUE TITLE
The use of tilde sign "~" cause vscode-r to raise "Unexpected end of input" error

### ISSUE THREAD

**Issue by mynanshan** [REditorSupport/languageserver#473]
Wherever I write `~` in the R script with vscode (e.g. in `lm()`), there will be an "Unexpected end of input" error raised by syntax check in the end of the script.
![image](https://user-images.githubusercontent.com/80438694/131200596-e3edf38d-6b66-4062-b133-b756677ae8fb.png)

* System and Editor: Windows 10
![image](https://user-images.githubusercontent.com/80438694/131200519-874c9cfd-dca8-4c5b-bd74-6dd2c4fb504c.png)

* Package: languageserver 0.3.11

**Comment by randy3k** [comment]
Pleaser double check your code. I am quite sure that it is a syntax error.

**Comment by mynanshan** [comment]
> Pleaser double check your code. I am quite sure that it is a syntax error.

Thanks, it is a syntax error. Sorry for my carelessness.
