### ISSUE TITLE
Auto-completion not available for all functions

### ISSUE THREAD

**Issue by raaj-winfred** [REditorSupport/languageserver#487]
Hello,
I recently installed R extension in VSCode and installed languageserver (install.packages("languageserver")). I tried to run a test code and I don't see auto-complete feature enabled for all functions. I have attached my settings.json for R, and screenshots of the code where auto-complete is appear and not appear. The auto-complete however appears for all functions in the Radian console. 
My system is Linux (OpenSUSE 15.1). Any help in resolving this issue is very much appreciated. Thanks
![Settings](https://user-images.githubusercontent.com/29850697/137593622-99217ab3-af97-4011-b8d7-53b5897823f7.png)
![auto-complete appear](https://user-images.githubusercontent.com/29850697/137593623-d59c747f-0448-4982-8360-abbdaa1f82d9.png)
![auto-complete not appear](https://user-images.githubusercontent.com/29850697/137593626-2f351f04-de58-4479-b89f-617c0081f39b.png)

.

**Comment by renkun-ken** [comment]
Could you go to the "Output" pane and find the log of "R Language Server" and see if the language server process is properly started.

**Comment by raaj-winfred** [comment]
Looks like the server is halted, this is the log I have at the "Output" pane
`[Error - 6:06:56 PM] Connection to server got closed. Server will not be restarted.
  This seems to be language server process. Aligning libraries.
  Determined new library locations: /home/raaj/languageserver-library, /usr/lib64/R/library
  Now .libpaths() is:
   /home/raaj/languageserver-library
   /usr/lib64/R/library
  Trying to requireNamespace of languageserver.
Error in languageserversetup::languageserver_startup() : 
  The languageserver package is not loadable. 
You can try running languageserver_install()
Execution halted`

I tried to run languageserver_install() in the r terminal in VSCode but I am getting the following message

`r$> languageserver_install()                                                                                                                                                   
Error in languageserver_install() : 
  could not find function "languageserver_install"`

**Comment by renkun-ken** [comment]
Is there a reason you use `languageserversetup` instead of directly installing `languageserver` from CRAN or GitHub?

**Comment by raaj-winfred** [comment]
If followed the instructions in [https://cran.r-project.org/web/packages/languageserversetup/readme/README.html](url) for the installation.
I did remotes::install_github("REditorSupport/languageserver") and here is the output:

`r$> remotes::install_github("REditorSupport/languageserver")                                                                                                       
Downloading GitHub repo REditorSupport/languageserver@HEAD
Installing 3 packages: openssl, httr, lintr
Installing packages into ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/openssl_1.4.5.tar.gz'
Content type 'application/x-gzip' length 1311351 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cloud.r-project.org/src/contrib/httr_1.4.2.tar.gz'
Content type 'application/x-gzip' length 159950 bytes (156 KB)
==================================================
downloaded 156 KB

trying URL 'https://cloud.r-project.org/src/contrib/lintr_2.0.1.tar.gz'
Content type 'application/x-gzip' length 219142 bytes (214 KB)
==================================================
downloaded 214 KB

* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-l:libssl.so.1.0.0 -l:libcrypto.so.1.0.0
** libs
rm -f aes.o base64.o bignum.o cert.o compatibility.o diffie.o envelope.o error.o hash.o info.o keygen.o keys.o onload.o openssh.o password.o pbkdf.o pem.o pkcs12.o pkcs7.o rand.o rsa.o signing.o ssl.o stream.o write.o x25519.o openssl.so bcrypt/libstatbcrypt.a bcrypt/bcrypt_pbkdf.o bcrypt/blowfish.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c aes.c -o aes.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c base64.c -o base64.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c bignum.c -o bignum.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c cert.c -o cert.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c compatibility.c -o compatibility.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c diffie.c -o diffie.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c envelope.c -o envelope.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c error.c -o error.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c hash.c -o hash.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c info.c -o info.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c keygen.c -o keygen.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c keys.c -o keys.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c onload.c -o onload.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c openssh.c -o openssh.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c password.c -o password.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c pbkdf.c -o pbkdf.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c pem.c -o pem.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c pkcs12.c -o pkcs12.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c pkcs7.c -o pkcs7.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c rand.c -o rand.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c rsa.c -o rsa.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c signing.c -o signing.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c ssl.c -o ssl.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c stream.c -o stream.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c write.c -o write.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c x25519.c -o x25519.o
x25519.c:30:13: warning: ‘R_read_raw_pubkey’ defined but not used [-Wunused-function]
 static SEXP R_read_raw_pubkey(SEXP x, int type){
             ^~~~~~~~~~~~~~~~~
x25519.c:13:13: warning: ‘R_read_raw_key’ defined but not used [-Wunused-function]
 static SEXP R_read_raw_key(SEXP x, int type){
             ^~~~~~~~~~~~~~
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c bcrypt/bcrypt_pbkdf.c -o bcrypt/bcrypt_pbkdf.o
gcc -I"/usr/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection  -c bcrypt/blowfish.c -o bcrypt/blowfish.o
ar rcs bcrypt/libstatbcrypt.a bcrypt/bcrypt_pbkdf.o bcrypt/blowfish.o
gcc -shared -L/usr/lib64/R/lib -L/usr/local/lib64 -o openssl.so aes.o base64.o bignum.o cert.o compatibility.o diffie.o envelope.o error.o hash.o info.o keygen.o keys.o onload.o openssh.o password.o pbkdf.o pem.o pkcs12.o pkcs7.o rand.o rsa.o signing.o ssl.o stream.o write.o x25519.o -Lbcrypt -lstatbcrypt -l:libssl.so.1.0.0 -l:libcrypto.so.1.0.0 -L/usr/lib64/R/lib -lR
installing to /home/raaj/R/x86_64-suse-linux-gnu-library/4.1/00LOCK-openssl/00new/openssl/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘openssl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/raaj/R/x86_64-suse-linux-gnu-library/4.1/00LOCK-openssl/00new/openssl/libs/openssl.so':
  /home/raaj/R/x86_64-suse-linux-gnu-library/4.1/00LOCK-openssl/00new/openssl/libs/openssl.so: undefined symbol: RSA_set0_factors
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1/openssl’
ERROR: dependency ‘openssl’ is not available for package ‘httr’
* removing ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1/httr’
ERROR: dependency ‘httr’ is not available for package ‘lintr’
* removing ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1/lintr’

The downloaded source packages are in
        ‘/tmp/RtmpTYqfU3/downloaded_packages’
Running `R CMD build`...
* checking for file ‘/tmp/RtmpTYqfU3/remotes74e415439e41/REditorSupport-languageserver-1bea3f0/DESCRIPTION’ ... OK
* preparing ‘languageserver’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘languageserver_0.3.11.tar.gz’
Installing package into ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
ERROR: dependency ‘lintr’ is not available for package ‘languageserver’
* removing ‘/home/raaj/R/x86_64-suse-linux-gnu-library/4.1/languageserver’
Warning messages:
1: In i.p(...) :
  installation of package ‘openssl’ had non-zero exit status
2: In i.p(...) : installation of package ‘httr’ had non-zero exit status
3: In i.p(...) : installation of package ‘lintr’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘/tmp/RtmpTYqfU3/file74e46f80a175/languageserver_0.3.11.tar.gz’ had non-zero exit status`

**Comment by eitsupi** [comment]
@raaj-winfred The error log says that libxml2 and libssl are not installed, so the R packages cannot be installed.
Do you have libxml2 and libssl installed?

https://github.com/r-lib/xml2/blob/02132a03c60d1cd9839d3d2ec0208882dd75caaf/DESCRIPTION#L44-L45
https://github.com/jeroen/openssl/blob/10a04b5afd24b966afd60349c1841cb7085c9fd4/DESCRIPTION#L20

**Comment by eitsupi** [comment]
@raaj-winfred The languageserver setup with the languageserversetup package will most likely not work on OpenSUSE. This is because the package management system is different from Ubuntu.

> Currently, the functionality is tested on 64bit versions of MS Windows 7, 10, Ubuntu 18.10 and MacOS El Capitan.

https://github.com/jozefhajnala/languageserversetup#platform-support

**Comment by raaj-winfred** [comment]
@eitsupi . The languageserver package did fail when I tried to install from CRAN. Upon further digging, I found that xml2 was installed but the openssl version was older. So, I updated the openssl to version 1.1.11 in my OpenSUSE system and tried to install languageserver again. Here is the output from the R console for xml2, openssl and languageserver
`r$> library("xml2")                                                                                                                                                

r$> library("openssl")                                                                                                                                             

r$> library("languageserver")   `

There are no errors in the output so the languageserver is installed now. I checked the output in the VSCode and now I am getting an error different than what I had in my first post

`Error in loadNamespace(x) : there is no package called ‘languageserver’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
[Error - 8:37:05 AM] Connection to server got closed. Server will not be restarted.`

Here is the output for remotes::install_github("REditorSupport/languageserver")

`Skipping install of 'languageserver' from a github remote, the SHA1 (4019bab4) has not changed since last install.
  Use `force = TRUE` to force installation`

**Comment by eitsupi** [comment]
@raaj-winfred Is anything written to your .Rprofile by using languageserversetup?

https://github.com/jozefhajnala/languageserversetup#removing-the-functionality

I don't think this is a problem with the languageserver package...

**Comment by raaj-winfred** [comment]
I searched through issues and found the one that I am having now (https://github.com/REditorSupport/languageserver/issues/380). The issue occurred in Archlinux and Windows Server 2019. Looks like the solution was found in Windows Server 2019. I followed the solution by setting my first line in .Rprofile as `.libPaths(c("/home/raaj/languageserver-library", .libPaths()))`
I also added 
`"r.lsp.args": [
     "-e",
     "writeLines(.libPaths(),'~/lsp.log')"
    ]`
in settings.json and the log out I got was
`/home/raaj/languageserver-library
/home/raaj/anaconda3/envs/r-env/lib/R/library`
Well, the issue still remains.

**Comment by raaj-winfred** [comment]
@eitsupi , @renkun-ken Looks like the issue is resolved, I went ahead and installed languageserver in the R environment that I created using anaconda `conda install -c conda-forge r-languageserver` and, there are no errors in the output for R languageserver in VSCode. All the features are now available. Thanks !
