### ISSUE TITLE
Language server can't start

### ISSUE THREAD

**Issue by taooceros** [REditorSupport/languageserver#502]
```
R Language Server (16236) started
[2021-12-02 20:35:34.318] Error: Total path length must be less than PATH_MAX: 260
Call: path_tidy(.Call(fs_path_, lapply(args, function(x) enc2utf8(as.character(x))), 
    ext))
Stack trace:
1: path_tidy(.Call(fs_path_, lapply(args, function(x) enc2utf8(as.character(x))), 
    ext))
2: path(start, path[!is_abs])
3: path_norm(path(start, path[!is_abs]))
4: fs::path_abs(str_texts, rootPath)
5: document_link_reply(id, uri, self$workspace, document, rootPath)
6: handler(self, item$id, item$params)
7: parse_callback(self, uri, version, result)
8: private$callback(result)
9: task$check()
10: self$parse_task_manager$check_tasks()
11: self$process_events()

[2021-12-02 20:35:34.343] exiting

[Error - 8:35:35 PM] Connection to server is erroring. Shutting down server.
[Error - 8:35:35 PM] Connection to server is erroring. Shutting down server.
[Error - 8:35:35 PM] Connection to server is erroring. Shutting down server.
R Language Server (16236) exited with exit code 0
```

**Comment by renkun-ken** [comment]
Would you like to provide a reproducible example of your code that triggers this error?

A path which is too long should be excluded already.

**Comment by taooceros** [comment]
It happens every time I open vscode. Probably because of some string in the file is too long? I don't want to share the file in public now so could I send it to your email?

**Comment by renkun-ken** [comment]
You could just fake a string that triggers the error.

**Comment by taooceros** [comment]
> You could just fake a string that triggers the error.

I don't know what triggers the error. It happens on starts up.

**Comment by renkun-ken** [comment]
> I don't want to share the file in public now so could I send it to your email?

OK

**Comment by eitsupi** [comment]
Is this a path length limitation on Windows?
File content may not the cause.
c.f. https://github.com/r-lib/fs/issues/269

**Comment by renkun-ken** [comment]
Yes, we know that limitation on Windows, therefore we have already filtered out those long strings in the document link provider. In your case, the error still occurs. So I need to take a look at it.

**Comment by renkun-ken** [comment]
@taooceros I received your document, and it looks like the filter actually works. All strings that are passed to `fs::path_abs()` contain at most 232 characters, which is within the limit of `PATH_MAX=260`.

I don't have a Windows machine to actually test it out. So I guess I could make the link provider more robust and ignore such errors.

**Comment by taooceros** [comment]
> @taooceros I received your document, and it looks like the filter actually works. All strings that are passed to `fs::path_abs()` contain at most 232 characters, which is within the limit of `PATH_MAX=260`.
> 
> I don't have a Windows machine to actually test it out. So I guess I could make the link provider more robust and ignore such errors.

Thank you so much! Could you share me with how the language server process the string length, so I can get it works for now?

**Comment by renkun-ken** [comment]
https://github.com/REditorSupport/languageserver/blob/master/R/link.R#L18

where `@col2<=@col1+256` is the filter. You could decrease it to a lower number like 100 or 200.

**Comment by taooceros** [comment]
> https://github.com/REditorSupport/languageserver/blob/master/R/link.R#L18
> 
> where `@col2<=@col1+256` is the filter. You could decrease it to a lower number like 100 or 200.

If I understand it right, it is check the length of a single line code and make sure it is lower than 256? So what I need to do is to split some of the long string in a single line to multiple line right?

**Comment by renkun-ken** [comment]
>If I understand it right, it is check the length of a single line code and make sure it is lower than 256? So what I need to do is to split some of the long string in a single line to multiple line right?

Yes you can do that to avoid passing those long strings to `fs::path_abs`.

**Comment by taooceros** [comment]
> > If I understand it right, it is check the length of a single line code and make sure it is lower than 256? So what I need to do is to split some of the long string in a single line to multiple line right?
> 
> Yes you can do that to avoid passing those long strings to `fs::path_abs`.

ok, I will try it out, thank you so much!

**Comment by taooceros** [comment]
Splitting long lines into multiple lines works. Thank you so much!!!

**Comment by renkun-ken** [comment]
@taooceros You could check if #506 works for you if you use the original code without splitting long lines.
