### ISSUE TITLE
Error: evaluation nested too deeply

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#513]
In Windows using vscode, opening a file outside the workspace might cause the following error:

```
R Language Server (2880) started
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?

Execution halted

R Language Server (2880) exited with exit code 1
```

**Comment by renkun-ken** [comment]
Looks like it only happens when I open `https://github.com/REditorSupport/vscode-R/blob/master/R/session/.Rprofile` as an external file in another workspace folder. In this case, this `.Rprofile` will start a new language server from `vscode-R/blob/master/R/session` folder where `.Rprofile` might source itself, which causes such infinite recursion.

**Comment by randy3k** [comment]
IICC, `languageserver` doesn't control souring the `.Rprofile` explicitly. Is it an issue specified to vscode-R?

**Comment by renkun-ken** [comment]
Yes, it might be specific to all language clients that try to start a language server from a folder where `.Rprofile` might source itself.

**Comment by renkun-ken** [comment]
If you go to the folder and start any R session, the error will occur. I think it should be fixed on vscode-R side.
