### ISSUE TITLE
Bug/possible syntax error in new languageserver 0.3.0

### ISSUE THREAD

**Issue by hermidalc** [REditorSupport/languageserver#52]
With the new version of languageserver 0.3.0 there appears to be a bug that causes linting to not work anymore.  When I try to lint files I get this:
```R
> library(languageserver)
> languageserver:::diagnose_file("test.R")
Error in range(start = list(line = line, character = result$ranges[[1]][1] -  : 
  `range` requires 'position' parameters!
```
Where in 0.2.9 it would work with same files.

**Comment by randy3k** [comment]
Sorry for introducing the bug. A new release will be out next week. Meanwhile, you would install dev version from the master branch.

**Comment by hermidalc** [comment]
> Sorry for introducing the bug. A new release will be out next week. Meanwhile, you would install dev version from the master branch.

I just reverted back to 0.2.9 it works well.
