### ISSUE TITLE
languageserver stopped working after updating to the latest R binary version 4.1.3

### ISSUE THREAD

**Issue by hhk-010** [REditorSupport/languageserver#531]
## Setup
~~~
- VScode: 1.65.2
- OS: Windows_NT x64 10.0.22000
- R: 4.1.3 (2022-03-10)
- Vscode-R: 2.4.0
- languageserver: 0.3.12
~~~

## VScode settings.JSON file
```
   "r.rpath.windows": "C:/PROGRA~1/R/R-41~1.3/bin/x64",
    "r.rterm.windows": "C:\\Users\\****\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\radian.exe",

   "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=C:\\Program Files\\R\\R-4.1.3\\bin\\R.exe"
    ],
   "r.bracketedPaste": true,
   "terminal.integrated.tabs.enabled": false,
    "r.plot.useHttpgd": true,
   "r.alwaysUseActiveTerminal": false,
    "r.lsp.debug": true,
   "r.lsp.diagnostics": true,
   "r.lsp.use_stdio": false,

  "r.lsp.args": [
        "--vanilla"
    ]
```
## what I did
- i needed to update to the lastest R version 4.1.3
- i uninstalled R version 4.1.2
- i removed installed packages 
- i installed the new version 
- i installed languageserver.
  
## what stopped working
1. languageserver
![Screenshot 2022-03-23 135326](https://user-images.githubusercontent.com/70376381/159686541-4d0d664d-d9bb-487c-9bd7-605c0a7aa0c1.png)

1. Vscode-R "HELP PAGES"  section

![Screenshot 2022-03-23 141135](https://user-images.githubusercontent.com/70376381/159686655-fe688516-ce5b-487c-ab23-bf2f7dc3befe.png)

## what is working
1. radian in VScode
3. Vscode-R "WORKSPACE" section

i tried reinstalling R and Vscode-R extension but to no benefit  
is there anything wrong i did. 
everthing was working perfectly well before updating. 
Thanks

**Comment by renkun-ken** [comment]
I cannot reproduce this. Looks like your setup is broken somehow.

**Comment by hhk-010** [comment]
> I cannot reproduce this. Looks like your setup is broken somehow.

After 10 hours of trials and errors, still I can't seem to find where the problem is 😓.  anyway THANKS ALOT for the reply and for your awesome work on R.

**Comment by hhk-010** [comment]
> > I cannot reproduce this. Looks like your setup is broken somehow.
> 
> After 10 hours of trials and errors, still I can't seem to find where the problem is 😓. anyway THANKS ALOT for the reply and for your awesome work on R.

I uninstalled Everything, delete all folders associated with VScode and R, Reinstall All..... and it worked

**Comment by hhk-010** [comment]
> > > I cannot reproduce this. Looks like your setup is broken somehow.
> > 
> > 
> > After 10 hours of trials and errors, still I can't seem to find where the problem is 😓. anyway THANKS ALOT for the reply and for your awesome work on R.
> 
> I uninstalled Everything, delete all folders associated with VScode and R, Reinstall All..... and it worked

**Comment by renkun-ken** [comment]
Looks like it was indeed some corrupted installation occurred.
