### ISSUE TITLE
How to disable code auto-format in VS Code?

### ISSUE THREAD

**Issue by mihaiconstantin** [REditorSupport/languageserver#544]
I am asking it here because I can't seem to find an answer in the docs or elsewhere. The posts that I find (e.g., [this StackOverflow question](https://stackoverflow.com/questions/57395681/getting-visual-studio-code-to-auto-format-r-code)) don't help.

**Comment by renkun-ken** [comment]
It has the same cause with #501. The folding provider is based on parsed data, which assumes that the code could be fully parsed.

**Comment by mihaiconstantin** [comment]
Oh, I see. This answers my question, thank you! Will close this one.

**Comment by mihaiconstantin** [comment]
I am sorry to comment again on this, but even with 

```json
"[r]": {
    "editor.formatOnSave": false
}
```

I am still facing the auto-format:

https://user-images.githubusercontent.com/20051042/166452382-80cd6125-4779-4658-b715-7fcde609d4fa.mov

Is this related to the linter? If so do you have any ideas on how to disable this behavior?

**Comment by renkun-ken** [comment]
You could tweak styler's tidyverse_style by putting the following in your `~/.Rprofile`:

```r
options(languageserver.formatting_style = function(options) {
  style <- styler::tidyverse_style(
    scope = "indention",
    indent_by = options$tabSize
  )
  style$space$start_comments_with_space <- NULL
  style
})
```

**Comment by mihaiconstantin** [comment]
Thank you @renkun-ken. This did it!
