### ISSUE TITLE
language server tooltips, colour picker, etc. not working after updating to R 4.2.

### ISSUE THREAD

**Issue by bighungryjames** [REditorSupport/languageserver#563]
![image](https://user-images.githubusercontent.com/47446784/180342355-43e7a991-bdb4-4f49-8497-d1878108d7c4.png)

language server tooltips are not working after updating R.

One of the Bioconductor packages I needed required updating R to latest version (4.2.1 currently), so I updated R using "installr" package. (Which could have been the problem.) Last version I used was R 4.1.2.

After the update, I re-opended the vscode, and noticed that all of the language server functionalities stopped working. The affected functionalities include function definition tooltips (as on the image above), colour picker.

I tried changing my network connection from my workplace's to my private one, but that did not affected anything.

I also tried relocating the languageserver lib from the default lib (C:/Program Files/R/R-4.2.1/library) to a directory inside My Documents via languageserversetup package, but that did not do anything either. Note that I also fixed the .Rprofile problem by appending the following code (I reversed slashes in the address in the code so that the directory separators work as intended):

```
# LanguageServer Setup Start (do not change this chunk)
# to remove this, run languageserversetup::remove_from_rprofile
if (requireNamespace('languageserversetup', quietly = TRUE)) {
  options(langserver_library = 'C:/Users/*****/Documents/languageserver-library')
  languageserversetup::languageserver_startup()
  unloadNamespace('languageserversetup')
}
# LanguageServer Setup End
```

**Comment by bighungryjames** [comment]
UPDATE: The problem disappeared as I reverted R to version 4.1.2. I guess this was a problem of version incompatibility. Since I have to use some packages in R 4.2.1 environment, I wish this issue is handled swiftly.

**Comment by renkun-ken** [comment]
Are you using the same library path with different R versions? Some packages with compiled code might not work properly if it is the case.

**Comment by bighungryjames** [comment]
> Are you using the same library path with different R versions? Some packages with compiled code might not work properly if it is the case.

Well, could you elaborate on the library path part? Before reverting to R 4.1.2, I was using R 4.2.1 and I uninstalled all the previous versions of R, reinstalling the packages I use via `install.packages()`. That being said, I also changed the vscode preferences r.path (or something like that) from 4.1.2 to 4.2.1.

The library paths I use are the default ones, C:/Program Files/R/R-***/library.

**Comment by renkun-ken** [comment]
Sounds like it is caused by your usage of `languageserversetup`? Would you try not using it and keep `.Rprofile` clean and install langaugeserver to your version-specific library path?

**Comment by bighungryjames** [comment]
Thank you for the quick responses. You're my savior! I deleted the languageserversetup package and the private library it created. Re-installing the languageserver without the languageserversetup restored the tooltips in R .1.2 environment.

However, I am not sure about the R 4.2.1. Is the current CRAN version of language server not compatible with R 4.2?

**Comment by bighungryjames** [comment]
![image](https://user-images.githubusercontent.com/47446784/180398158-7f0ed2ac-ac5b-4bcc-9245-575792974298.png)
UPDATE: When I removed everything and cleanly install R 4.2.1 and Rtools 42, The tooltip disappearing still exists and the colour picker is not there. However, the r environment watching (the right panel with the global environment variables etc.) are working fine.

**Comment by renkun-ken** [comment]
Would you like to enable `r.lsp.debug` in vscode and go to "Output" -> "R Language Server" and see if there is an error when vscode-R tries to spawn a language server process.

**Comment by bighungryjames** [comment]
Thank you for the guides! It says as the following:
"R language server (undefined) started"

**Comment by bighungryjames** [comment]
I tried (from searching similar cases) running the languageserver manually:
`languageserver::run(debug=TRUE)`
However, the following Error message appears:
```
> languageserver::run(debug=TRUE)
[2022-07-22 21:58:30.954] connection type: stdio
[2022-07-22 21:58:31.519] Error: stdin connection close
Call: stdin_read_line()
Stack trace:
1: stdin_read_line()
2: self$read_line()
3: self$read_header()
4: self$fetch(blocking = FALSE)
[2022-07-22 21:58:31.604] exiting
```

**Comment by renkun-ken** [comment]
Does it work if you run

```r
languageserver::run(debug=TRUE, port = 13579)
```

What's your vscode settings of vscode-R extension (`r.*`)?

**Comment by bighungryjames** [comment]
> Does it work if you run
> 
> ```r
> languageserver::run(debug=TRUE, port = 13579)
> ```
> 
> What's your vscode settings of vscode-R extension (`r.*`)?

Thank you very much!!!!!
The problem was the vscode settings. The JSON file contained the following lines:
```
    "r.rpath.windows": "C:\\Program Files\\R\\R-4.1.2\\bin\\x64\\R.exe",
    "r.rterm.windows": "C:\\Program Files\\R\\R-4.2.1\\bin\\x64\\R.exe",
    "files.associations": {
        "*.rmd": "markdown"
    },
    "r.libPaths": [
        "C:\\Program Files\\R\\R-4.2.1\\library\\"
    ],
    "r.lsp.debug": true
```

So I changed the `rpath` to `"C:\\Program Files\\R\\R-4.2.1\\bin\\x64\\R.exe"` and re-loaded vscode. That fixed everything! Thank you very, very much.

In the meantime, as a newbie coder in R and python, maybe I should get more used to this vscode development environments. Thank you for all your time!

**Comment by renkun-ken** [comment]
Glad to know it works for you now.

The experience of using multiple versions of R might be improved via https://github.com/REditorSupport/vscode-R/pull/1143.
