### ISSUE TITLE
Can't turn off linter

### ISSUE THREAD

**Issue by JohnCoene** [REditorSupport/languageserver#570]
Hi,

I've got `"r.lsp.diagnostics": false` but the linter is still linting. Has been working for ages but for some reason it no longer does.
Is there something I am missing?

**Comment by renkun-ken** [comment]
I cannot reproduce the problem. Are you using the latest release of languageserver and vscode-R?

**Comment by JohnCoene** [comment]
Sorry, I can't seem to be able to reproduce it either.
Thanks again for the amazing suite of packages!

**Comment by mihaiconstantin** [comment]
@renkun-ken I updated the packages you indicated, and no improvements, sadly. I rolled back to `v2.5.2` and it works as expected.

**Comment by JohnCoene** [comment]
It's strange issue that I have trouble replicating myself

**Comment by dsg38** [comment]
I have the same issue - and it can temporarily be fixed by toggling the setting as @mihaiconstantin has said (see below). But then returns whenever I reopen vs code. I'm on mac os 12.5.1, vs code 1.71.2, r extension 2.5.3

> I experience the same after the `v2.5.3` update. The problem goes away if I toggle the `R › Lsp: Diagnostics › Enable diagnostics.` setting if VSCode. However, the problem is back upon running `Developer: Reload Window`. Until now, I was following your suggestion here, i.e., [#544 (comment)](https://github.com/REditorSupport/languageserver/issues/544#issuecomment-1116873424).

**Comment by vertesy** [comment]
I have the same issue on macOS Ventura, VS code `1.80.2`, `R v2.8.1`.
