### ISSUE TITLE
Server failed to start probably due to hard-coded installation path ERROR

### ISSUE THREAD

**Issue by qqlearn123** [REditorSupport/languageserver#579]
The language server fails to start because it tries to parse an **xml** file in one of my R package (called _xsef_) and cannot find **xmlTreeParse** function.

I am using **vscode (v1.72.2)**, **R plugin for vscode (v2.6.0)**, **R (v4.0.3)**, **languageserver (v0.3.13)**.

The error message is like:

---
[2022-10-15 12:09:05:322] Error: could not find function "xmlTreeParse"
Call: xmlTreeParse(system.file("extdata/xschema.xml", package="xsef"))
Stack trace:
1: get(x, envir = ns)
2: FUN(X[[i]], ...)
3: vapply(private$objects, function(x) {
  is.function(get(x, envir = ns))
}, logical(1L), USE.NAMES = FALSE)
4: initialize(...)
5: PackageNamespace$new(pkgname)
6: self$get_namespace(pkgname)
7: self$load_package(package)
8: self$workspace$load_packages(packages)
9: resolve_callack(self, uri, version, result)
10: private$callback(result)
11: task$check()
12: self$resolve_task_manager$check_tasks()
13: self$process_events()

[2022-10-15 12:09:05:322] exiting

---
Thanks for your help!

**Comment by renkun-ken** [comment]
Looks like your package xsef defined a symbol that requires `xmlTreeParse` on load. Is it possible that we see the source code of `xsef` or would you like to share the places where you use `xmlTreeParse` in the package so that we could build a reproducible example?

**Comment by qqlearn123** [comment]
Thanks for your time looking into it.

Yes, it is indeed. There is one R file in my **xsef** package which have this line in it:
_.xschema = xmlTreeParse(system.file("extdata/xschema.xml", package="xsef"))_

Actually the **xsef** package depends on the XML package (which have **xmlTreeParse** function), so installing and using it independently have no problem for me. Not sure how it affects the languageserver's failure to start.

**Comment by renkun-ken** [comment]
When the error occurs, is XML properly installed? Does `getNamespace("xsef")$.xschema` work properly in your R terminal?

**Comment by euclidy** [comment]
`getNamespace("xsef")$.xschema` gives me the same error - _Error: could not find function "xmlTreeParse"_

But, if I just type **R** and **require(xsef)**, no issues. And, **head(.xschema)** in R terminal works fine as well.

**Comment by qqlearn123** [comment]
getNamespace("xsef")$.xschema gives me the same error - Error: could not find function "xmlTreeParse"

But, if I just type R and require(xsef), no issues. And, head(.xschema) in R terminal works fine as well.

**Comment by qqlearn123** [comment]
Is there a solution or workaround to this issue? I tried lazy late loading and use XML:::xmlTreePase, both did not work.

Is it possible that the languageserver just pass through without error out in such scenario?

**Comment by renkun-ken** [comment]
Would you like to try #582 and see if it works for you?

**Comment by qqlearn123** [comment]
Think the original cause is hard-coded installation path which can be solved by using '--no-staged-install'.
