### ISSUE TITLE
Autocompletion per document or for the whole workspace

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#58]
The current implementation of symbol provider is workspace-wide, i.e., if you open and edit 10 R script files, then all documents are parsed and all symbols are shared in the completion list when I edit one file.

This can sometimes be annoying if I need to edit a simple script and a very long script that defines a lot of symbols at the same time.

I'm wondering if it makes sense to provide symbols per document, or according to referenced documents (as mentioned in #20).

**Comment by randy3k** [comment]
I guess we will need to check if the files are coming from the same package. We may need to open a [workspace](https://github.com/REditorSupport/languageserver/blob/master/R/workspace.R#L85) for each independent file.

**Comment by renkun-ken** [comment]
Global namespace no longer infinitely grows with #123 merged. So the behavior is good enough for now.
