### ISSUE TITLE
Completion in VSCode does not work for loaded packages

### ISSUE THREAD

**Issue by lsdch** [REditorSupport/languageserver#580]
Using R version 4.2.1

Having loaded the `stringr` package, `str_*` functions should be suggested in autocompletion choices. This is not the case in VSCode editor : 
![image](https://user-images.githubusercontent.com/17616580/196257242-4311b2ba-f058-449a-9d76-4b5851d7fbe2.png)

VSCode settings : 
```
"r.plot.useHttpgd": true,
"r.rterm.linux": "/home/lsdch/.local/bin/radian",
"r.bracketedPaste": true,
"r.session.levelOfObjectDetail": "Normal",
 ```

Output panel in VSCode states that `R Language Server (177550) started`, and shows no errors

Completion does work in radian console, or in the editor when the namespace is specified 

![image](https://user-images.githubusercontent.com/17616580/196258119-5d238241-2495-4444-ab6d-bd075c60acd0.png)

![image](https://user-images.githubusercontent.com/17616580/196258722-f1e0c0eb-724b-4486-91ab-70be089a4a92.png)

**Comment by renkun-ken** [comment]
Does the auto-completion work properly for other `library(pkg)` or it just doesn't work for `library(stringr)` in your case?

Cannot reproduce it yet. If you enable `r.lsp.debug` and type the following:

```r
library(stringr)
str
```

The following log should be seen:

```

[2022-10-18 09:00:34.448] token: {
  "full_token": "str",
  "right_token": "",
  "package": null,
  "accessor": "",
  "token": "str"
}

[2022-10-18 09:00:34.453] bracket is  

[2022-10-18 09:00:34.453] completions:  {
  "init_count": 73,
  "final_count": 73,
  "time": 0.0057,
  "isIncomplete": false
}
```

**Comment by lsdch** [comment]
LSP debug log shows that package `xmlparsedata` could not be loaded because its installation was faulty (compiled with another R version). I just reinstalled this package and everything works perfectly. 
Thanks a lot @renkun-ken !
