### ISSUE TITLE
range formatting ignores current indentation

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#59]
The following code is a minimal example to demonstrate that range formatting ignores the current indentation.

When editing the function body of `f`, the cursor has two-space indentation initially, copy-paste the code from `x <- rnorm(n)` to `coef(m)` with indentation included to the cursor and I find the code removes its indentation after formatting (triggered by formatOnPaste in vscode). Formatting the whole document will fix this indentation issue.

Similar behavior occurs when I copy the whole `t` expression and paste it inside the function body of `g` at the cursor of two-space indentation.

```r
n <- 1000
t <- system.time({
  x <- rnorm(n)
  y <- 3 + 2 * x + rnorm(n)
  m <- lm(y ~ x)
  coef(m)
})

f <- function(n) {
  ## paste here and the two-space indentaion is lost
x <- rnorm(n)
y <- 3 + 2 * x + rnorm(n)
m <- lm(y ~ x)
coef(m)
}

g <- function(x) {
  ## paste here and the two-space indentation is lost
t <- system.time({
  x <- rnorm(n)
  y <- 3 + 2 * x + rnorm(n)
  m <- lm(y ~ x)
  coef(m)
})
}
```

I guess it's because `range_formatting_reply` ignores the indentation of the current cursor.

**Comment by randy3k** [comment]
Perhaps we could detect the indentation of the original first line and prepend it to all the lines.

**Comment by renkun-ken** [comment]
Thanks for the fix!

For the demo code above, if I copy 

```r
  x <- rnorm(n)
  y <- 3 + 2 * x + rnorm(n)
  m <- lm(y ~ x)
  coef(m)
```

which has indentation of 2 spaces.

And start a new line in the body of `g`, I will automatically get an indentation of 2 spaces, as the following shows where `|` represents my cursor:

```r
g <- functon(x) {
  |
}
```

If I paste the code at the cursor, I'll get

```r
g <- functon(x) {
    x <- rnorm(n)
    y <- 3 + 2 * x + rnorm(n)
    m <- lm(y ~ x)
    coef(m)
}
```

which has 4-space indentation. However, the desired result for me is still 2-space indentation because it fits the indentation of the function body.

I'm wondering if it makes sense that the copied string be styled (which removes its indentation) and put it to the cursor (which repects the indentation of the cursor as just implemented)?

**Comment by randy3k** [comment]
It is a VS code specific behavior. I don’t think we have any control of it.

**Comment by renkun-ken** [comment]
I'm a bit confused about which behavior is vscode-specific, or provided by vscode extensions. But the latest version is good enough for me. Thanks!

**Comment by randy3k** [comment]
The language server is only allowed to return what the protocol is allowed. For range formatting, we could only return a list of text edits (i.e., modified text). We cannot control the extra indentation based on the current cursor. In fact, the language server doesn't know where the cursor is at.
