### ISSUE TITLE
package::function() autocompletion doesn't include re-exported functions

### ISSUE THREAD

**Issue by francisbarton** [REditorSupport/languageserver#590]
In RStudio, I can use autocomplete to complete function names such as:

`purrr::set_names()` and `rvest::read_html()`.

These are functions that belong originally to other packages (`rlang` and `xml2` respectively in these examples) but are also exported from `purrr` and `rvest`.

In R in VSCode, if I try to autocomplete `rvest::` I don't get `read_html()` as a dropdown option. I can only get it by starting with `xml2::`. Is there a way that languageserver could read in these borrowed functions as options for autocomplete?

**Comment by randy3k** [comment]
Looks like `objects` doesn't return the re-exported functions.

```
r$> "set_names" %in% objects(asNamespace("purrr"))
[1] FALSE

r$> "set_names" %in% getNamespaceExports(asNamespace("purrr"))
[1] TRUE
```

**Comment by francisbarton** [comment]
That's awesomely responsive 😲✨
