### ISSUE TITLE
Provide roxygen entries in auto-completion

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#60]
For package developer, it would be great to provide roxygen entries in auto-completion. 
For example, entries like `@param`, `@export` in lines starting with `#'` can be provided to facilitate documentation writing.

```r
#' Test function
#' @param x an object
#' @param check a function
#' @export
#' @examples
#' test(NULL, is.null)
#' test(0, is.null)
test <- function(x, check) {
  if (check(x)) {
    x
  } else {
    stop("Check failed")
  }
}
```

Another related issue is that writing a line of roxygen comment and starting a new line should make the new line automatically start with `#'`. I'm not sure if it is a LSP thing (maybe onTypeFormatter?) or I should go to `vscode-R` extension (since I'm using vscode) for this feature?

**Comment by andycraig** [comment]
Both these would be nice features.

Open vscode-R issue about `#'`: https://github.com/Ikuyadeu/vscode-R/issues/85

**Comment by renkun-ken** [comment]
Related FR: https://github.com/Ikuyadeu/vscode-R/issues/124

**Comment by randy3k** [comment]
It is the job of the editor specific plugin to handle the auto completions for `@param` etc. Language servers should not handle generic snippets. With the same reason, it is the job of the editor to insert `#'`. (For your information, [`sublime-ide-r`](https://github.com/REditorSupport/sublime-ide-r) does insert `#'` when `enter` is hit.)
