### ISSUE TITLE
Disable style diagnotics

### ISSUE THREAD

**Issue by fristzzz** [REditorSupport/languageserver#603]
Hi all,
In Rstudio, I can turn off style diagnotics in code settings, 
but is there any way to do the same thing in vscode and nvim+lspconfig?
🥲

**Comment by longze360** [comment]
how about this in settting.json:

```
"r.lsp.diagnostics": false,
"r.lsp.diagnostics.lintr.enabled": false,

```

**Comment by fristzzz** [comment]
> 

Thanks for your help!
Seems the only way is like you said, `"r.lsp.diagnostics": false".  This will disable all the diagnostic messages.

Then I found a new problem, that is error messages such as undefined variable can only be shown in Rstudio. Like this:
in Rstudio:
![rstudio](https://user-images.githubusercontent.com/91342166/224236256-18bcd069-6b3a-4237-ae03-b2e1a56bbc63.png)

While in vscode and neovim, it only shows style diagnostics.:
![vscode](https://user-images.githubusercontent.com/91342166/224236668-77b24e38-76e2-4279-8b6b-9ab05f093314.png)

Wonder how to configure it.

**Comment by fristzzz** [comment]
> how about this in settting.json:
> 
> ```
> "r.lsp.diagnostics": false,
> "r.lsp.diagnostics.lintr.enabled": false,
> ```

Thanks for your help!
Seems the only way is like you said, `"r.lsp.diagnostics": false".  This will disable all the diagnostic messages.

Then I found a new problem, that is error messages such as undefined variable can only be shown in Rstudio. Like this:
in Rstudio:
![rstudio](https://user-images.githubusercontent.com/91342166/224236256-18bcd069-6b3a-4237-ae03-b2e1a56bbc63.png)

While in vscode and neovim, it only shows style diagnostics.:
![vscode](https://user-images.githubusercontent.com/91342166/224236668-77b24e38-76e2-4279-8b6b-9ab05f093314.png)

Wonder how to configure it.

**Comment by randy3k** [comment]
The diagnostics are provided by lintr. Lintr has a similar linter called object usage linter. Though I didn’t have very good experience with it.

**Comment by Yunuuuu** [comment]
Just turn off `object_useage_linter` in `.lintr` file, details see <https://lintr.r-lib.org/articles/lintr.html>

**Comment by fristzzz** [comment]
> Just turn off `object_useage_linter` in `.lintr` file, details see https://lintr.r-lib.org/articles/lintr.html

Thanks for answering! But recently I prefer to choose RStudio to write R codes or Rmd.
