### ISSUE TITLE
On-type formatter adds extra indentations after pipes

### ISSUE THREAD

**Issue by Darxor** [REditorSupport/languageserver#607]
When using `"editor.formatOnType": true` in VSCode pipes with multi-line function calls cause extra indentations to appear.

This example will keep correct indentation on line 4 after pressing Enter
``` r 
df |>
  mutate(a = b) |>
  mutate() |>
```

However, this example will cause indentation on line 6 to double up:
``` r 
df |>
  mutate(
    a = b
  ) |>
  mutate() |>
```

<details>
<summary>Here's a config I use for styler inside languageserver:</summary>

```r
options(languageserver.formatting_style = function(options) {
  styler::tidyverse_style(
    scope = "tokens",
    strict = TRUE,
    start_comments_with_one_space = FALSE,
    indent_by = options$tabSize
  )
})
```

</details>

**Comment by renkun-ken** [comment]
@Darxor Would you like to try `remotes::install_github("REditorSupport/languageserver#615")` and see if it works for you?

**Comment by Darxor** [comment]
Yes, it does seem to work properly for me now. Thanks for the fix!
