### ISSUE TITLE
Error in Neovim: “attempt to compare string with number”

### ISSUE THREAD

**Issue by klmr** [REditorSupport/languageserver#609]
Based on the error stack traceback, this is related to #481. Unfortunately #565 did not fix it, and the error persists in the current HEAD revision (adc2189eff742fec42f3ece6df5c3c33062607b3).

To reproduce the issue, create a file containing the following and open it in Neovim with LSP configured to use ‘languageserver’:

```r
a =
b = 2
```

Here’s the full error message:

```
Error executing vim.schedule lua callback: /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:431: attempt to compare string with number
stack traceback:
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:431: in function 'add'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:468: in function 'get_diagnostics'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:1162: in function 'show'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:724: in function 'set'
        /opt/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:206: in function 'handler'
        /opt/local/share/nvim/runtime/lua/vim/lsp.lua:1049: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by randy3k** [comment]
It sounds like an issue of lintr reporting the row number and column number: https://github.com/REditorSupport/languageserver/blob/master/R/diagnostics.R#L17

We may need to check if the numbers are NAs?

**Comment by klmr** [comment]
Are you able to reproduce the issue? Otherwise I am happy to patch my local ‘languageserver’ version with instrumentation code. Unfortunately I know absolutely nothing about the Lua/client side of things.

**Comment by randy3k** [comment]
It has been a while since I used neovim and it seems that neovim supports LSP officially. Could you share how you configure neovim to setup R languageserver?

**Comment by klmr** [comment]
Here’s a minimal configuration (the config is macOS but on a Linux system using the path `~/.config/nvim` instead of `~/Library/Preferences/nvim` should have the sam effect):

```sh
cat ~/Library/Preferences/nvim/init.lua
```

```lua
vim.opt.runtimepath:append('~/Library/Preferences/nvim/mason.nvim')
vim.opt.runtimepath:append('~/Library/Preferences/nvim/nvim-lspconfig')

require('mason').setup()
require('lspconfig').r_language_server.setup{}
```

Afterwards, do the following inside the nvim config path to initialise the LSP support plugins:

```sh
git clone --depth 1 git@github.com:williamboman/mason.nvim.git
git clone --depth 1 git@github.com:neovim/nvim-lspconfig.git

nvim +:MasonInstall\ r-languageserver
```

And restart Neovim afterwards.

… in theory these plugins are not necessary but in practice the manual nvim LSP configuration is so complicated that it is recommended to use these plugins.

**Comment by klmr** [comment]
Hi, I went ahead and locally modified `diagnostic_range` to include logging the return value (via `dput`). And, indeed, for the snippet above I am getting the following values after this line:

https://github.com/REditorSupport/languageserver/blob/adc2189eff742fec42f3ece6df5c3c33062607b3/R/diagnostics.R#L28

```r
result == structure(
  list(
    filename = "/path/to/test.r",
    line_number = 2L,
    column_number = 0L,
    type = "style",
    message = "Indentation should be 4 spaces but is 0 spaces.",
    line = "b = 2",
    ranges = list(c(0L, 4L)),
    linter = "indentation_linter"
  ),
  class = c("lint", "list")
)

cols == c(4, NA)
```

So there’s a `NA` length, just as you suspected. Does this help?

**Comment by milanglacier** [comment]
> Here’s a minimal configuration (the config is macOS but on a Linux system using the path `~/.config/nvim` instead of `~/Library/Preferences/nvim` should have the sam effect):
> 
> ```shell
> cat ~/Library/Preferences/nvim/init.lua
> ```
> 
>  ```lua
> vim.opt.runtimepath:append('~/Library/Preferences/nvim/mason.nvim')
> vim.opt.runtimepath:append('~/Library/Preferences/nvim/nvim-lspconfig')
> 
> require('mason').setup()
> require('lspconfig').r_language_server.setup{}
> ```
> 
> Afterwards, do the following inside the nvim config path to initialise the LSP support plugins:
> 
> ```shell
> git clone --depth 1 git@github.com:williamboman/mason.nvim.git
> git clone --depth 1 git@github.com:neovim/nvim-lspconfig.git
> 
> nvim +:MasonInstall\ r-languageserver
> ```
> 
> And restart Neovim afterwards.
> 
> … in theory these plugins are not necessary but in practice the manual nvim LSP configuration is so complicated that it is recommended to use these plugins.

If `languageserver` package (`install.packages("languageserver"`) is installed in the `R` in the `PATH`, this config should be enough:

```lua
vim.opt.runtimepath:append('~/Library/Preferences/nvim/nvim-lspconfig')

require('lspconfig').r_language_server.setup{}
```
remember `git clone --depth 1 git@github.com:neovim/nvim-lspconfig.git`.

There's no need to use mason to install r-language-server

**Comment by milanglacier** [comment]
with neovim 0.9, I can't reproduce the problem. I guess maybe neovim 0.9 has improved the robustness of error handling.

In fact if you go to the source code of the traceback, in the latest commit the function `add` has been moved to line 396.

**Comment by klmr** [comment]
@milanglacier I am running nvim v0.9.0 and I can still reproduce this bug. The line numbers in the stack trace did change slightly, but the line number now is not 396, it’s 406:

```
Error executing vim.schedule lua callback: /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:406: attempt to compare string with number
stack traceback:
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:406: in function 'add'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:422: in function 'add_all_diags'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:443: in function 'get_diagnostics'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:1191: in function 'show'
        /opt/local/share/nvim/runtime/lua/vim/diagnostic.lua:703: in function 'set'
        /opt/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:236: in function 'handler'
        /opt/local/share/nvim/runtime/lua/vim/lsp.lua:1057: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by randy3k** [comment]
@klmr Could you check if #614 fixes the issue?

```
remotes::install_github("REditorSupport/languageserver#614")
```

**Comment by chunyunma** [comment]
Sadly, the same error occurred for me today, even after applying the #614 patch.
neovim version = 0.9.1
The error would only appear when I am working `.Rmd` files, but not with `.R` file type.
