### ISSUE TITLE
spawn: bash failed with exit code 127 and signal 0. 

### ISSUE THREAD

**Issue by hopezh** [REditorSupport/languageserver#635]
Unable to install `r-languageserver` in `neovim` through `mason`. 

Got the following error message:
```
 Failed
    ◍ r-languageserver
      ▼ Displaying full log
        Cloning git repository "https://github.com/mason-org/r-languageserver.git"…
        Cloning into '.'...
        From https://github.com/mason-org/r-languageserver
         * tag               v0.3.16    -> FETCH_HEAD
        + ./bin/install v0.3.16
        ./bin/install: line 15: exec: R: not found
        spawn: bash failed with exit code 127 and signal 0. 
```

Screen image: 
![image](https://github.com/REditorSupport/languageserver/assets/23435810/d0bd0384-533c-47d0-a54e-1d72c174a833)

I'm using: 
Ubuntu-22.04, in 5.15.90.1-microsoft-standard-WSL2, in Windows 11
Neovim: v0.10.0-dev-837+g389165cac-Homebrew
My own Neovim config: [oatLazyVim](https://github.com/hopezh/oatLazyVim)

**Comment by SelenZzz** [comment]
bump

**Comment by JadAbouHawili** [comment]
it says why, you need R installed
