### ISSUE TITLE
Section collapsing issues

### ISSUE THREAD

**Issue by kylebutts** [REditorSupport/languageserver#643]
The language server has preferences over the way sections collapse (namely, collapse up to a set of 2 blank lines:
https://github.com/REditorSupport/languageserver/blob/7f7605b55a6cbe05e0033b40f21e87408c06e102/R/section.R#L19 and https://github.com/REditorSupport/languageserver/blob/7f7605b55a6cbe05e0033b40f21e87408c06e102/R/section.R#L319-L337

I'm wondering if changing this could be part of the available settings? I personally, like extra whitespace, so it would be nice to configure. I would be happy to open a PR. I think the steps would be:
1. Add `nline_to_break_succession` option to `S6` option `Settings`
2. In section.R, use `lsp_settings$get("nline_to_break_succession")` here: https://github.com/REditorSupport/languageserver/blob/7f7605b55a6cbe05e0033b40f21e87408c06e102/R/section.R#L19

**Comment by renkun-ken** [comment]
It is perfectly okay to send a PR on this if you find it useful.
