### ISSUE TITLE
Request textDocument/rangeFormatting failed

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#67]
Create a document like the following:

```r
cols <- c("a", "b", "c", "d", "e",
  "f", "g", "h", "i", "j", "k", "l",
  "m", "n", "o", "p")

cols_new <- test("file1",
  names = c(1:10, 15:20),
  colnames = c())
```

And then copy the elements of `cols` (from "a" to "p" without `c()`) and paste them into the parentheses in `colnames = c()` and an internal error of languageserver occurs:

```
internal error:  <text>:3:22: unexpected ')'
2:   "f", "g", "h", "i", "j", "k", "l",
3:   "m", "n", "o", "p"))
                        ^

[Error - 4:14:43 PM] Request textDocument/rangeFormatting failed.
  Message: <text>:3:22: unexpected ')'
2:   "f", "g", "h", "i", "j", "k", "l",
3:   "m", "n", "o", "p"))
                        ^

  Code: -32603 
```

**Comment by randy3k** [comment]
It is VSCode specific issue, but there is more going on here. The problem is, in `range formatting`, we always get the full lines of the selection.
https://github.com/REditorSupport/languageserver/blob/94a8db03369cf393606c4a570689707a68ba7bc4/R/formatting.R#L77-L80

When you paste "a" to "p", the text being formatted is
```
  colnames = c("a", "b", "c", "d", "e",
  "f", "g", "h", "i", "j", "k", "l",
  "m", "n", "o", "p")))
```

That's why we get an error.

The easiest fix is to catch the possible error of `style_text` since we cannot predict what will be passed to it.

Does VSCode really expect to run formatting for every paste? Sometime user may copy and paste an incomplete piece of code and obviously we don't want to format it.

**Comment by renkun-ken** [comment]
In vscode, there are `formatOnType`, `formatOnPaste`, and `formatOnSave` options. I think such formatting error can be suppressed unless debug mode is on.

**Comment by randy3k** [comment]
I believe that the error is suppressed when debug mode is off, isn't it?

**Comment by renkun-ken** [comment]
My debug mode is off but this still appears.

**Comment by randy3k** [comment]
Note that you will need to restart VSCode.

**Comment by randy3k** [comment]
The problem is more complicated when I thought.

```
foo <- function(
		x = 1,
		y = 2
	) {
	# body
}

```
If I paste `z = 1` to replace `y = 2`. I got

```
foo <- function(
		x = 1,
		z <- 1
	) {
	# body
}
```

**Comment by randy3k** [comment]
I guess we need to check if the selection is from the beginning to the end of all the lines included.

**Comment by renkun-ken** [comment]
This example is caused by assignment operator fix, even if you select the full line, the formatting would make this happen, doesn't it?

**Comment by randy3k** [comment]
Yes, it would still be an issue. But at least it is not triggered all the times. A better solution is to check the scope of the selection. But it can be difficult in some situations.

**Comment by renkun-ken** [comment]
Maybe we can turn off operator replace by default?

**Comment by renkun-ken** [comment]
Use `format selection` in vscode will make this happen too.

Operator replacement is dangerous because `<-` and `=` are not always interchangeable. I think we should turn if off by default as an argument of `style_text`.
