### ISSUE TITLE
Handle encoding headers?

### ISSUE THREAD

**Issue by krassowski** [REditorSupport/languageserver#77]
We tried using [python-jsonrpc-server](https://github.com/palantir/python-jsonrpc-server) multiplexer for [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp), however it failed with R languageserver, while most other LSP servers work ok. Would you be willing to accept a PR allowing to parse encoding and other headers, such as [this](https://github.com/palantir/python-jsonrpc-server/blob/develop/pyls_jsonrpc/streams.py#L95):

`Content-Type: application/vscode-jsonrpc; charset=utf8\r\n`

Currently, I get `Error in self$read_content(nbytes) : Unexpected non-empty line` when this is present - it seems that only `Content-Length` is supported. It would be good enough if the server did not error on the additional header (the header/contents separation is defined by an empty line, so there should be no problem with detecting variable length headers).

Some relevant discussion: https://github.com/krassowski/jupyterlab-lsp/pull/50 (we also struggle with the compilation time of the languageserver and its dependencies and are looking to conda - e.g. https://anaconda.org/gwerbin/r-languageserver, to get precompiled binaries - would you be interested in us setting up a conda package for your project? Or maybe you know another solution to the slow compilation process?)

**Comment by randy3k** [comment]
The current master has addressed it, see fb6cd22901590b10eeb1fc93ce7930e5beeab5d4.

**Comment by krassowski** [comment]
Ops, sorry for the noise in this case - and thank you for all your brilliant work!

**Comment by randy3k** [comment]
No worries. Most of the development of the server is still following the LSP protocol 2.x. I only discovered the change of the header information recently when I was reading the spec. 

I don't have any experience with the conda package. I am happy to help if you need any specific help.

**Comment by krassowski** [comment]
@randy3k conda-forge recipe seems to be live now: https://anaconda.org/conda-forge/r-languageserver :) see [this comment](https://github.com/krassowski/jupyterlab-lsp/pull/50#issuecomment-537484574) for the relevant discussion.
