### ISSUE TITLE
Auto-complete with full list of package objects on `::` and `:::`

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#79]
Currently, typing `pkg::` does not trigger auto-completion to show the full list of exported objects of `pkg`. Neither does `pkg:::` show the full list of exported and non-exported objects of `pkg`.

It would be convinient to trigger auto-completion on both `::` and `:::` so that user could easily explorer the functions in a package without knowing in advance the exact starting letters of the function the user wants.

**Comment by randy3k** [comment]
should be an easy fix c387af7.

**Comment by randy3k** [comment]
In vscode, I believe you could always use `ctrl+space` to trigger the completion menu.

**Comment by renkun-ken** [comment]
Looks good. Thanks! One minor issue, the icon of every list item in `:::` looks like an option rather than object or function:

![image](https://user-images.githubusercontent.com/4662568/66089647-c2674d00-e5b2-11e9-983c-05144a6257eb.png)

It seems that auto-completion items triggered by `:::` do not get the correct types.

**Comment by randy3k** [comment]
this line controls the icon https://github.com/REditorSupport/languageserver/blob/c387af7552ff7333e41dd54484e62bd85d3d30e3/R/completion.R#L99-L99

Perhaps you could tell which icon looks more reasonable. I don't have much experience with vscode.

**Comment by randy3k** [comment]
Oh, I was wrong. Ignore my last post.

**Comment by randy3k** [comment]
the icon issue should be addressed by e791c41

**Comment by renkun-ken** [comment]
Thanks!
