### ISSUE TITLE
Provide diagnostics on non-installed packages

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#80]
The current diagnotics use `lintr` which is mainly focused on style diagnostics. However, code correctness is largely not diagnosed. An obvious one is to check if there is any `library(pkg)` call that points to non-installed package. Similar calls include `require(pkg)`, `loadNamespace("pkg")`, `requireNamespace("pkg")`, `pkg::foo`, `pkg:::bar`.

The recently released [`lintr v2.0.0`](https://www.jimhester.com/post/lintr-2-0-0/) supports [customized lintr](https://cran.r-project.org/web/packages/lintr/vignettes/creating_linters.html). I'm not sure if it is better to use this or separate correctness checks from linting.

**Comment by randy3k** [comment]
I am not sure, users can always define their own linters and specify those in their `.lintr` configuration.

Of course, if you are ambitious enough, it is would be useful to the general R community if you put the extra linters together and create a separate R package, say `morelintr`.
Then in the README, we could point the interested readers to the package.

**Comment by renkun-ken** [comment]
This is only a mimic behavior of RStudio which detects required not installed packages in a script and notify the user if they want to install them. I think this feature makes sense and makes it convenient to work with scripts given by other users though I personally don't use it much.

**Comment by renkun-ken** [comment]
https://github.com/jimhester/lintr/pull/547 provides a `missing_package_linter` so that upgrading to the latest development version of lintr and adding this linter to the `.lintr` config file will resolve this issue.
