### ISSUE TITLE
Need customizable formatting scopes

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/languageserver#85]
It would be very nice to allow users to customize the range/document formatting scopes at https://github.com/REditorSupport/languageserver/blob/master/R/formatting.R#L95.

```r
    # check if the selection contains complete lines
    if (character1 != 0 || character2 < ncodeunit(lastline)) {
        scope <- "line_breaks"
    } else {
        scope <- "tokens"
    }
```

For me, I only need `indentation` level of scopes under all circumstances, or otherwise my code 

```r
data <- fst::read_fst("/path/to/my/data.fst",
  columns = c("symbol", "date", "time", "pre_close", "close",
    "volume","turnover","ret"),
  as.data.table = TRUE)
```

which I think is concise and good enough will always be formatted as

```r
data <- fst::read_fst("/path/to/my/data.fst",
    columns = c(
        "symbol", "date", "time", "pre_close", "close",
        "volume", "turnover", "ret"
    ),
    as.data.table = TRUE
)
```

which I think is a bit clumsy.

We can add some options to `languageserver` such as `languageserver.partial_formatting_scope = "line_breaks"` and `langaugeserver.complete_formatting_scope = "tokens"` to allow user to customize the behavior without adding too much complexity.

**Comment by randy3k** [comment]
I think a better solution is to allow user specifying their own [style](https://styler.r-lib.org/articles/customizing_styler.html).

**Comment by renkun-ken** [comment]
Sorry I forget about that. I agree with you that it would be much more customizable to allow users to use own style.

Therefore, does it mean we could expose `styler::tidyverse_style()` part as an option to user?

```r
styler::style_file(temp_file,
        transformers = styler::tidyverse_style(indent_by = options$tabSize)
    )
```

For the scope issue, do we have to define two options of styles so that partial selection and complete line selection are handled separately?

**Comment by randy3k** [comment]
I am not sure yet, it seems overly complicated to allow two styles.

**Comment by renkun-ken** [comment]
I agree. I'm also thinking about a better solution to this.

**Comment by renkun-ken** [comment]
@randy3k, one solution that I think is simple and elegant is that languageserver itself defines its default style as `tidyverse_style` but `force_assignment_op` is disabled.

```r
get_style <- function(...) {
    style <- getOption("languageserver.formatting_style")
    if (is.null(style)) {
        style <- styler::tidyverse_style(...)
        style$token$force_assignment_op <- NULL
    } else {
        style <- style(...)
    }
    style
}
```

So I can specify my own style in my Rprofile 

```r
options(languageserver.formatting_style = function(...) {
  styler::tidyverse_style(tokens = "indention", ...)
}
```

If you are okay with it, I'll send a PR for this.

**Comment by randy3k** [comment]
I am not sure about disabling the assignment operator transformation in default. It will for sure introduce inconsistency between lintr and styler, i.e., while `lintr` complaints about the `=` operator, `styler` doesn't fix it.

**Comment by renkun-ken** [comment]
Sorry for forgetting about lintr diagnostics. The only problem here is assignment operator inconsistencies. 

What about only disabling assignment operator fix in partial selection, and all other styling are kept so that user still use `languageserver.formatting_style` option to customize style?
