### ISSUE TITLE
Automatic Formatting Not Working 

### ISSUE THREAD

**Issue by lyh970817** [REditorSupport/languageserver#95]
It seems that the automatic formatting is not working in neovim or atom on my computer. The style_file function works fine in R. Diagnostics and code completion also work fine.

**Comment by renkun-ken** [comment]
Would you like to provide an example and do you perform document formatting or range formatting (format selection). For range formatting, would you provide the range of you select in your document?

**Comment by randy3k** [comment]
Please also make sure that you have the latest languageserver.

**Comment by lyh970817** [comment]
> Would you like to provide an example and do you perform document formatting or range formatting (format selection). For range formatting, would you provide the range of you select in your document?

Thanks for replies of both of you. I was thinking this plugin would support automatic formatting of the document as you type in content, but reading through the documentation I'm not sure if this is what it does. It works fine when running document formatting and range formatting commands in vim, so I was able to set up some sort of formatting as you type myself.

**Comment by randy3k** [comment]
We has not yet supported formatting in typing. As I t could be quite computational expensive and performance could be an issue (and I probably won’t use it), it’s not in our top list.
